module.exports = function(grunt){

	var tutorialOrder = [
		{
			category:'Dojo 1.8 Tutorials',
			tutorials: [
				'ajax',
				'animation',
				'arrays',
				'augmenting_objects',
				'beyond_dojo',
				'build',
				'cdn',
				'charting',
				'charting_advanced',
				'checkboxes',
				'creating_stores',
				'data_modeling',
				'datagrid',
				'declaration',
				'declare',
				'deferreds',
				'device_optimized_builds',
				'dialogs_tooltips',
				'dijit_layout',
				'dojo_config',
				'dojo_data',
				'dojo_date',
				'dom_functions',
				'editor',
				'effects',
				'events',
				'form_manager',
				'gfx',
				'hash',
				'hello_dojo',
				'hitch',
				'i18n',
				'intro_dojo_store',
				'jsonp',
				'key_events',
				'loading_overlay',
				'menus',
				'mobile/tweetview/getting_started',
				'mobile/tweetview/intro_tweetview',
				'mobile/tweetview/packaging',
				'mobile/tweetview/settings',
				'mobile/tweetview/starting_tweetview',
				'modern_dojo',
				'modules',
				'nodelist_extensions',
				'populating_datagrid',
				'promises',
				'realtime_stores',
				'recipes/app_controller',
				'recipes/custom_widget',
				'recipes/doh_testsuite',
				'selects',
				'selects_using_stores',
				'sliders',
				'start',
				'store_driven_grid',
				'store_driven_tree',
				'templated',
				'themes_buttons_textboxes',
				'understanding_widgetbase',
				'uploader',
				'using_query',
				'validation',
				'working_grid',
			]
		}
	];

	return tutorialOrder;
}
