//>>built
define("dojo/touch","./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(F,v,w,G,H,g,m,n,x,d){function l(b,a,e){return t&&e?function(b,a){return g(b,e,a)}:y?function(e,d){var c=g(e,a,function(c){d.call(this,c);p=(new Date).getTime()}),I=g(e,b,function(c){(!p||(new Date).getTime()>p+1E3)&&d.call(this,c)});return{remove:function(){c.remove();I.remove()}}}:function(a,e){return g(a,b,e)}}function J(b){do if(void 0!==b.dojoClick)return b;
while(b=b.parentNode)}function z(b,a,e){if(!n.isRight(b)){var f=J(b.target);if(h=!b.target.disabled&&f&&f.dojoClick)if(r=(q="useTarget"==h)?f:b.target,q&&b.preventDefault(),A=b.changedTouches?b.changedTouches[0].pageX-d.global.pageXOffset:b.clientX,B=b.changedTouches?b.changedTouches[0].pageY-d.global.pageYOffset:b.clientY,C=("object"==typeof h?h.x:"number"==typeof h?h:0)||4,D=("object"==typeof h?h.y:"number"==typeof h?h:0)||4,!E){E=!0;var k=function(c){h=q?w.isDescendant(d.doc.elementFromPoint(c.changedTouches?
c.changedTouches[0].pageX-d.global.pageXOffset:c.clientX,c.changedTouches?c.changedTouches[0].pageY-d.global.pageYOffset:c.clientY),r):h&&(c.changedTouches?c.changedTouches[0].target:c.target)==r&&Math.abs((c.changedTouches?c.changedTouches[0].pageX-d.global.pageXOffset:c.clientX)-A)<=C&&Math.abs((c.changedTouches?c.changedTouches[0].pageY-d.global.pageYOffset:c.clientY)-B)<=D};d.doc.addEventListener(a,function(c){n.isRight(c)||(k(c),q&&c.preventDefault())},!0);d.doc.addEventListener(e,function(c){if(!n.isRight(c)&&
(k(c),h)){u=(new Date).getTime();var a=q?r:c.target;"LABEL"===a.tagName&&(a=w.byId(a.getAttribute("for"))||a);var b=c.changedTouches?c.changedTouches[0]:c,e=document.createEvent("MouseEvents");e._dojo_click=!0;e.initMouseEvent("click",!0,!0,c.view,c.detail,b.screenX,b.screenY,b.clientX,b.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,0,null);setTimeout(function(){g.emit(a,"click",e);u=(new Date).getTime()},0)}},!0);b=function(c){d.doc.addEventListener(c,function(a){!a._dojo_click&&((new Date).getTime()<=
u+1E3&&!("INPUT"==a.target.tagName&&G.contains(a.target,"dijitOffScreen")))&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),"click"==c&&(("INPUT"!=a.target.tagName||"radio"==a.target.type||"checkbox"==a.target.type)&&"TEXTAREA"!=a.target.tagName&&"AUDIO"!=a.target.tagName&&"VIDEO"!=a.target.tagName)&&a.preventDefault())},!0)};b("click");b("mousedown");b("mouseup")}}}var s=5>m("ios"),t=m("pointer-events")||m("MSPointer"),f=function(){var b={},a;for(a in{down:1,move:1,
up:1,cancel:1,over:1,out:1})b[a]=m("MSPointer")?"MSPointer"+a.charAt(0).toUpperCase()+a.slice(1):"pointer"+a;return b}(),y=m("touch-events"),E,h,q=!1,r,A,B,C,D,u,p,k;t?x(function(){d.doc.addEventListener(f.down,function(b){z(b,f.move,f.up)},!0)}):y&&x(function(){function b(a){var b=H.delegate(a,{bubbles:!0});6<=m("ios")&&(b.touches=a.touches,b.altKey=a.altKey,b.changedTouches=a.changedTouches,b.ctrlKey=a.ctrlKey,b.metaKey=a.metaKey,b.shiftKey=a.shiftKey,b.targetTouches=a.targetTouches);return b}k=
d.body();d.doc.addEventListener("touchstart",function(a){p=(new Date).getTime();var b=k;k=a.target;g.emit(b,"dojotouchout",{relatedTarget:k,bubbles:!0});g.emit(k,"dojotouchover",{relatedTarget:b,bubbles:!0});z(a,"touchmove","touchend")},!0);g(d.doc,"touchmove",function(a){p=(new Date).getTime();var e=d.doc.elementFromPoint(a.pageX-(s?0:d.global.pageXOffset),a.pageY-(s?0:d.global.pageYOffset));e&&(k!==e&&(g.emit(k,"dojotouchout",{relatedTarget:e,bubbles:!0}),g.emit(e,"dojotouchover",{relatedTarget:k,
bubbles:!0}),k=e),g.emit(e,"dojotouchmove",b(a))||a.preventDefault())});g(d.doc,"touchend",function(a){p=(new Date).getTime();var e=d.doc.elementFromPoint(a.pageX-(s?0:d.global.pageXOffset),a.pageY-(s?0:d.global.pageYOffset))||d.body();g.emit(e,"dojotouchend",b(a))})});v={press:l("mousedown","touchstart",f.down),move:l("mousemove","dojotouchmove",f.move),release:l("mouseup","dojotouchend",f.up),cancel:l(n.leave,"touchcancel",t?f.cancel:null),over:l("mouseover","dojotouchover",f.over),out:l("mouseout",
"dojotouchout",f.out),enter:n._eventHandler(l("mouseover","dojotouchover",f.over)),leave:n._eventHandler(l("mouseout","dojotouchout",f.out))};return F.touch=v});
//# sourceMappingURL=touch.js.map