/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
(function(a,h){var l,n,e=function(){},d=function(a){for(var c in a)return 0;return 1},m={}.toString,f=function(a){return m.call(a)=="[object Function]"},k=function(a){return m.call(a)=="[object String]"},b=function(a){return m.call(a)=="[object Array]"},o=function(a,c){if(a)for(var b=0;b<a.length;)c(a[b++])},j=function(a,c){for(var b in c)a[b]=c[b];return a},s=function(a,c){return j(Error(a),{src:"dojoLoader",info:c})},p=1,c=function(){return"_"+p++},g=function(a,c,b){return Ea(a,c,b,0,g)},i=this,
q=i.document,u=q&&q.createElement("DiV"),r=g.has=function(a){return f(t[a])?t[a]=t[a](i,q,u):t[a]},t=r.cache=h.hasCache;r.add=function(a,c,b,g){(t[a]===void 0||g)&&(t[a]=c);return b&&r(a)};for(var A in a.has)r.add(A,a.has[A],0,1);var w=0,I=[],R=0,D=e,S=e,x;g.isXdUrl=e;g.initSyncLoader=function(a,c,b){R||(R=a,D=c,S=b);return{sync:"sync",xd:"xd",arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:I,modules:J,execQ:N,getModule:U,injectModule:ga,setArrived:Z,signal:K,finishExec:aa,execModule:ba,
dojoRequirePlugin:R,getLegacyMode:function(){return w},holdIdle:function(){T++},releaseIdle:function(){ca()}}};var P=location.protocol,v=location.host,B=!v;g.isXdUrl=function(a){if(B||/^\./.test(a))return!1;if(/^\/\//.test(a))return!0;return(a=a.match(/^([^\/\:]+\:)\/\/([^\/]+)/))&&(a[1]!=P||a[2]!=v)};r.add("dojo-force-activex-xhr",!q.addEventListener&&window.location.protocol=="file:");r.add("native-xhr",typeof XMLHttpRequest!="undefined");if(r("native-xhr")&&!r("dojo-force-activex-xhr"))x=function(){return new XMLHttpRequest};
else{A=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"];var F;for(l=0;l<3;)try{if(F=A[l++],new ActiveXObject(F))break}catch(C){}x=function(){return new ActiveXObject(F)}}g.getXhr=x;r.add("dojo-gettext-api",1);g.getText=function(a,c,b){var g=x();g.open("GET",ha(a),!1);g.send(null);if(g.status==200||!location.host&&!g.status)b&&b(g.responseText,c);else throw s("xhrFailed",g.status);return g.responseText};var E=new Function("return eval(arguments[0]);");g.eval=function(a,c){return E(a+"\r\n////@ sourceURL="+
c)};var G={},K=g.signal=function(a,c){var g=G[a];o(g&&g.slice(0),function(a){a.apply(null,b(c)?c:[c])})},V=g.on=function(a,c){var b=G[a]||(G[a]=[]);b.push(c);return{remove:function(){for(var a=0;a<b.length;a++)if(b[a]===c){b.splice(a,1);break}}}},W=[],L={},z=[],M={},y={},H=[],J={},ua="",Y={},ia={};A={};var ja=function(a){var c,b,g,i;for(c in ia)b=ia[c],(g=c.match(/^url\:(.+)/))?Y[Fa(g[1],a)]=b:c=="*now"?i=b:c!="*noref"&&(Y[da(c,a).mid]=b);i&&i(va(a));ia={}},wa=function(a,c,b){c.splice(0,c.length);
var g,i=0;for(g in a)c.push([g,a[g]]),a[g]==b&&(i=g);c.sort(function(a,c){return c[0].length-a[0].length});for(a=0;a<c.length;)b=c[a++],b[2]=RegExp("^"+b[0].replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})+"(/|$)"),b[3]=b[0].length+1;return i},Ga=function(a,c){var b=a.name;b||(b=a,a={name:b});a=j({main:"main",mapProg:[]},a);a.location=(c||"")+(a.location?a.location:b);a.reverseName=wa(a.packageMap,a.mapProg,b);if(!a.main.indexOf("./"))a.main=a.main.substring(2);j(L,a.paths);M[b]=
a;y[b]=b},ka=function(a,c){for(var b in a){if(b=="waitSeconds")g.waitms=(a[b]||0)*1E3;b=="cacheBust"&&(ua=a[b]?k(a[b])?a[b]:(new Date).getTime()+"":"");if(b=="baseUrl"||b=="combo")g[b]=a[b];if(b=="async"){var i=a[b];g.legacyMode=w=k(i)&&/sync|legacyAsync/.test(i)?i:!i?"sync":!1;g.async=!w}a[b]!==t&&(g.rawConfig[b]=a[b],b!="has"&&r.add("config-"+b,a[b],0,c))}if(!g.baseUrl)g.baseUrl="./";/\/$/.test(g.baseUrl)||(g.baseUrl+="/");for(b in a.has)r.add(b,a.has[b],0,c);o(a.packages,Ga);for(n in a.packagePaths)o(a.packagePaths[n],
function(a){Ga(a,n+"/")});wa(j(L,a.paths),z);o(a.aliases,function(a){k(a[0])&&(a[0]=RegExp("^"+a[0].replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})+"$"));W.push(a)});wa(j(y,a.packageMap),H);if(a.cache)ja(),ia=a.cache,a.cache["*noref"]&&ja();K("config",[a,g.rawConfig])};r("dojo-cdn");var Q,la,xa,ma=q.getElementsByTagName("script");for(l=0;l<ma.length&&!xa;l++)if((la=ma[l].getAttribute("src"))&&(xa=la.match(/(.*)\/?dojo\.js(\W|$)/i)))a.baseUrl=Q=a.baseUrl||h.baseUrl||xa[1],(la=ma[l].getAttribute("data-dojo-config")||
ma[l].getAttribute("djConfig"))&&(A=g.eval("({ "+la+" })","data-dojo-config"));g.rawConfig={};ka(h,1);ka(a,1);ka(A,1);if(r("dojo-cdn"))M.dojo.location=Q,M.dijit.location=Q+"../dijit/",M.dojox.location=Q+"../dojox/";var ea=function(a){T++;o(a.deps,ga);ca()},Ea=function(a,i,d,f,o){if(k(a)){if((i=U(a,f,!0))&&i.executed)return i.result;throw s("undefinedModule",a);}b(a)||(ka(a),a=i,i=d);if(b(a))if(a.length){for(var d="require*"+c(),q,p=[],u=0;u<a.length;){q=a[u++];if(q in{exports:1,module:1})throw s("illegalModuleId",
q);p.push(U(q,f))}i=j(na("",d,0,""),{injected:2,deps:p,def:i||e,require:f?f.require:g});J[i.mid]=i;ea(i);a=T&&g.async;T++;ba(i,a);ca();i.executed||N.push(i);$()}else i&&i();return o},va=function(a){if(!a)return g;var c=a.require;if(!c)c=function(b,g,i){return Ea(b,g,i,a,c)},a.require=j(c,g),c.module=a,c.toUrl=function(c){return Fa(c,a)},c.toAbsMid=function(c){return ya(c,a)},c.syncLoadNls=function(c){var c=da(c,a),b=J[c.mid];if(!b||!b.executed)if(X=Y[c.mid]||Y[c.cacheId])oa(X),b=J[c.mid];return b&&
b.executed&&b.result};return c},N=[],pa=[],O={},Ra=function(a){a.injected=1;O[a.mid]=1;a.url&&(O[a.url]=a.pack||1)},Z=function(a){a.injected=2;delete O[a.mid];a.url&&delete O[a.url];d(O)&&(qa(),w=="xd"&&(w="sync"))},Sa=g.idle=function(){return!pa.length&&d(O)&&!N.length&&!T},za=function(a,c){for(var b=0;b<c.length;b++)if(c[b][2].test(a))return c[b];return 0},Ha=function(a){for(var c=[],b,g,a=a.replace(/\\/g,"/").split("/");a.length;)b=a.shift(),b==".."&&c.length&&g!=".."?(c.pop(),g=c[c.length-1]):
b!="."&&c.push(g=b);return c.join("/")},na=function(a,c,b,i,d){var f=g.isXdUrl(i);return{pid:a,mid:c,pack:b,url:i,executed:0,def:0,isXd:f,isAmd:!!(f||M[a]&&M[a].isAmd),cacheId:d}},Ia=function(a,c,b,g,i,d,j,e){var q,k,p,u=0;p=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||p&&!c)return na(0,a,0,a);else{a=Ha(p?c.mid+"/../"+a:a);if(/^\./.test(a))throw s("irrationalPath",a);if(p=(c=c&&c.pack&&c.pack.mapProg)&&za(a,c)||za(a,d)){c=p[1];a=a.substring(p[3]);q=b[c];if(!a)a=q.main;k=a;u=q.reverseName+"/"+a;
a=c+"/"+a}else c="";var m=0;o(W,function(c){var b=a.match(c[0]);b&&b.length>0&&(m=f(c[1])?a.replace(c[0],c[1]):c[1])});if(m)return Ia(m,0,b,g,i,d,j,e);if(b=g[a])return e?na(b.pid,b.mid,b.pack,b.url,u):g[a]}g=(p=za(a,j))?p[1]+a.substring(p[3]-1):c?q.location+"/"+k:r("config-tlmSiblingOfDojo")?"../"+a:a;/(^\/)|(\:)/.test(g)||(g=i+g);g+=".js";return na(c,a,q,Ha(g),u)},da=function(a,c){return Ia(a,c,M,J,g.baseUrl,H,z)},Ja=function(a,c,b){return a.normalize?a.normalize(c,function(a){return ya(a,b)}):ya(c,
b)},Ka=0,U=function(a,c,b){var g,i;(g=a.match(/^(.+?)\!(.*)$/))?(i=U(g[1],c,b),w=="sync"&&!i.executed&&(ga(i),i.injected===2&&!i.executed&&(T++,ba(i),ca()),i.executed?ra(i):N.unshift(i)),i.executed===5&&!i.load&&ra(i),i.load?(g=Ja(i,g[2],c),a=i.mid+"!"+(i.dynamic?++Ka+"!":"")+g):(g=g[2],a=i.mid+"!"+ ++Ka+"!waitingForPlugin"),a={plugin:i,mid:a,req:va(c),prid:g}):a=da(a,c);return J[a.mid]||!b&&(J[a.mid]=a)},ya=g.toAbsMid=function(a,c){return da(a,c).mid},Fa=g.toUrl=function(a,c){var b=da(a+"/x",c),
g=b.url;return ha(b.pid===0?a:g.substring(0,g.length-5))},La={injected:2,executed:5,def:3,result:3};Q=function(a){return J[a]=j({mid:a},La)};var Ta=Q("require"),Ua=Q("exports"),Va=Q("module"),sa={},Aa=0,ra=function(a){var c=a.result;a.dynamic=c.dynamic;a.normalize=c.normalize;a.load=c.load;return a},Wa=function(a){var c={};o(a.loadQ,function(b){var g=Ja(a,b.prid,b.req.module),i=a.dynamic?b.mid.replace(/waitingForPlugin$/,g):a.mid+"!"+g,g=j(j({},b),{mid:i,prid:g,injected:0});J[i]||Ma(J[i]=g);c[b.mid]=
J[i];Z(b);delete J[b.mid]});a.loadQ=0;var b=function(a){for(var b=a.deps||[],g=0;g<b.length;g++)(a=c[b[g].mid])&&(b[g]=a)},g;for(g in J)b(J[g]);o(N,b)},aa=function(a){g.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=Aa++;o(a.provides,function(a){a()});a.loadQ&&(ra(a),Wa(a));for(l=0;l<N.length;)N[l]===a?N.splice(l,1):l++},Xa=[],ba=function(a,c){if(a.executed===4)return g.trace("loader-circular-dependency",[Xa.concat(b).join("->")]),!a.def||c?sa:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return sa;
var b=a.mid,i=a.deps||[],d,j=[],o=0;for(a.executed=4;o<i.length;){d=i[o++];d=d===Ta?va(a):d===Ua?a.cjs.exports:d===Va?a.cjs:ba(d,c);if(d===sa)return a.executed=0,g.trace("loader-exec-module",["abort",b]),sa;j.push(d)}g.trace("loader-run-factory",[a.mid]);var b=a.def,e;I.unshift(a);if(r("config-dojo-loader-catches"))try{e=f(b)?b.apply(null,j):b}catch(q){K("error",a.result=s("factoryThrew",[a,q]))}else e=f(b)?b.apply(null,j):b;a.result=e===void 0&&a.cjs?a.cjs.exports:e;I.shift(a);aa(a)}return a.result},
T=0,$=function(){if(!T){T++;D();for(var a,c,b=0;b<N.length;)a=Aa,c=N[b],ba(c),a!=Aa?(D(),b=0):b++;ca()}},ca=function(){T--;Sa()&&K("idle",[])};r("dojo-loader-eval-hint-url")===void 0&&r.add("dojo-loader-eval-hint-url",1);var ha=function(a){a+="";return a+(ua?(/\?/.test(a)?"&":"?")+ua:"")},Ma=function(a){var c=a.plugin;c.executed===5&&!c.load&&ra(c);var b=function(c){a.result=c;Z(a);aa(a);$()};c.load?c.load(a.prid,a.req,b):c.loadQ?c.loadQ.push(a):(c.loadQ=[a],N.unshift(c),ga(c))},X=0,fa=0,Ba=0,oa=
function(a,c){Ba=1;if(r("config-dojo-loader-catches"))try{a===X?X.call(null):g.eval(a,r("dojo-loader-eval-hint-url")?c.url:c.mid)}catch(b){K("error",s("evalModuleThrew",c))}else a===X?X.call(null):g.eval(a,r("dojo-loader-eval-hint-url")?c.url:c.mid);Ba=0},ga=function(a){var c=a.mid,b=a.url;if(!a.executed&&!a.injected&&!(O[c]||a.url&&(a.pack&&O[a.url]===a.pack||O[a.url]==1)))if(Ra(a),a.plugin)Ma(a);else{var i=function(){Na(a);a.injected!==2&&(Z(a),j(a,La));w?!I.length&&$():$()};if(X=Y[c]||Y[a.cacheId])g.trace("loader-inject",
["cache",a.mid,b]),oa(X,a),i();else{if(w)if(a.isXd)w=="sync"&&(w="xd");else if(!(a.isAmd&&w!="sync")){var d=function(d){if(w=="sync"){I.unshift(a);oa(d,a);I.shift();Na(a);a.cjs||(Z(a),aa(a));if(a.finish){var d=c+"*finish",j=a.finish;delete a.finish;Ca(d,["dojo",("dojo/require!"+j.join(",")).replace(/\./g,"/")],function(a){o(j,function(c){a.require(c)})});N.unshift(U(d))}i()}else(d=S(a,d))?(oa(d,a),i()):(fa=a,g.injectUrl(ha(b),i,a),fa=0)};g.trace("loader-inject",["xhr",a.mid,b,w!="sync"]);if(r("config-dojo-loader-catches"))try{g.getText(b,
w!="sync",d)}catch(f){K("error",s("xhrInjectFailed",[a,f]))}else g.getText(b,w!="sync",d);return}g.trace("loader-inject",["script",a.mid,b]);fa=a;g.injectUrl(ha(b),i,a);fa=0}}},Da=function(a,c,b){g.trace("loader-define-module",[a.mid,c]);var i=a.mid;if(a.injected===2)return K("error",s("multipleDefine",a)),a;j(a,{deps:c,def:b,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(c){a.cjs.exports=c}}});for(var d=0;d<c.length;d++)c[d]=U(c[d],a);w&&!O[i]&&(ea(a),N.push(a),$());Z(a);if(!f(b)&&
!c.length)a.result=b,aa(a);return a},Na=function(a,c){for(var b=[],g,i;pa.length;)i=pa.shift(),c&&(i[0]=c.shift()),g=i[0]&&U(i[0])||a,b.push([g,i[1],i[2]]);ja(a);o(b,function(a){ea(Da.apply(null,a))})},ta=0,qa=e,Oa=e,qa=function(){ta&&clearTimeout(ta);ta=0},Oa=function(){qa();g.waitms&&(ta=setTimeout(function(){qa();K("error",s("timeout",O))},g.waitms))};r.add("ie-event-behavior",q.attachEvent&&(typeof opera==="undefined"||opera.toString()!="[object Opera]"));var Pa=function(a,c,b,g){return r("ie-event-behavior")?
(a.attachEvent(b,g),function(){a.detachEvent(b,g)}):(a.addEventListener(c,g,!1),function(){a.removeEventListener(c,g,!1)})},Ya=Pa(window,"load","onload",function(){g.pageLoaded=1;q.readyState!="complete"&&(q.readyState="complete");Ya()}),Qa=q.getElementsByTagName("script")[0],Za=Qa.parentNode;g.injectUrl=function(a,c,b){Oa();var b=b.node=q.createElement("script"),g=Pa(b,"load","onreadystatechange",function(a){var a=a||window.event,b=a.target||a.srcElement;if(a.type==="load"||/complete|loaded/.test(b.readyState))g(),
c&&c()});b.type="text/javascript";b.charset="utf-8";b.src=a;Za.insertBefore(b,Qa);return b};g.log=function(){try{for(var a=0;a<arguments.length;a++);}catch(c){}};g.trace=e;var Ca=function(a,c,i){var d=arguments.length,j=0,o=["require","exports","module"];j||(j=d==1?[0,o,a]:d==2?b(a)?[0,a,c]:f(c)?[a,o,c]:[a,[],c]:[a,c,i]);g.trace("loader-define",j.slice(0,2));if((d=j[0]&&U(j[0]))&&!O[d.mid])ea(Da(d,j[1],j[2]));else if(!r("ie-event-behavior")||Ba)pa.push(j);else{d=d||fa;if(!d)for(a in O)if((o=J[a])&&
o.node&&o.node.readyState==="interactive"){d=o;break}d?(ja(d),ea(Da(d,j[1],j[2]))):K("error",s("ieDefineFailed",j[0]));$()}};Ca.amd={vendor:"dojotoolkit.org"};j(j(g,h.loaderPatch),a.loaderPatch);V("error",function(a){try{if(console.error(a),a instanceof Error)for(var c in a);}catch(b){}});j(g,{uid:c,cache:Y,packs:M});i.define?K("error",s("defineAlreadyDefined",0)):(i.define=Ca,i.require=g);Q=A.deps||a.deps||h.deps;A=A.callback||a.callback||h.callback;g.boot=Q||A?[Q||[],A]:0})(this.dojoConfig||this.djConfig||
this.require||{},{async:0,cdn:"//ajax.googleapis.com/ajax/libs/dojo/1.8.0/",hasCache:{"config-selectorEngine":"acme","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:".",name:"dojo"},{location:"../dijit",name:"dijit"},{location:"../dojox",name:"dojox"},{location:"../docs",main:"guide",name:"docs"},{location:"../util/doh",name:"doh"}]});
require({cache:{"dojo/main":function(){define(["./_base/kernel","./has","require","./_base/sniff","./_base/lang","./_base/array","./ready","./_base/declare","./_base/connect","./_base/Deferred","./_base/json","./_base/Color","require","./_base/browser","./_base/loader"],function(a,h,l,n,e,d,m){a.config.isDebug&&l(["./_firebug/firebug"]);var f=a.config.require;f&&(f=d.map(e.isArray(f)?f:[f],function(a){return a.replace(/\./g,"/")}),a.isAsync?l(f):m(1,function(){l(f)}));return a})},"dojo/_base/kernel":function(){define(["../has",
"./config","require","module"],function(a,h,l,n){var e,d={},m={},f={config:h,global:this,dijit:d,dojox:m},d={dojo:["dojo",f],dijit:["dijit",d],dojox:["dojox",m]},n=l.packs&&l.packs[n.id.match(/[^\/]+/)[0]].packageMap||{};for(e in n)d[e]?d[e][0]=n[e]:d[e]=[n[e],{}];for(e in d)n=d[e],n[1]._scopeName=n[0],h.noGlobals||(this[n[0]]=n[1]);f.scopeMap=d;f.baseUrl=f.config.baseUrl=l.baseUrl;f.isAsync=l.async;f.locale=h.locale;n="$Rev$".match(/\d+/);f.version={major:1,minor:7,patch:4,flag:"",revision:n?+n[0]:
NaN,toString:function(){var a=f.version;return a.major+"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+")"}};f.eval=function(){};Function("d","d.eval = function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(f);f.exit=function(){};typeof console!="undefined"||(console={});for(var d=["assert","count","debug","dir","dirxml","error","group","groupEnd","info","profile","profileEnd","time","timeEnd","trace","warn","log"],k,n=0;k=d[n++];)console[k]||function(){var a=k+"";console[a]=
"log"in console?function(){var d=Array.apply({},arguments);d.unshift(a+":");console.log(d.join(" "))}:function(){};console[a]._fake=!0}();a.add("dojo-debug-messages",!!h.isDebug);a("dojo-debug-messages")?(f.deprecated=function(a,d,j){a="DEPRECATED: "+a;d&&(a+=" "+d);j&&(a+=" -- will be removed in version: "+j);console.warn(a)},f.experimental=function(a,d){var j="EXPERIMENTAL: "+a+" -- APIs subject to change without notice.";d&&(j+=" "+d);console.warn(j)}):f.deprecated=f.experimental=function(){};
if(h.modulePaths){f.deprecated("dojo.modulePaths","use paths configuration");a={};for(e in h.modulePaths)a[e.replace(/\./g,"/")]=h.modulePaths[e];l({paths:a})}f.moduleUrl=function(a,d){f.deprecated("dojo.moduleUrl()","use require.toUrl","2.0");var j=null;a&&(j=l.toUrl(a.replace(/\./g,"/")+(d?"/"+d:"")+"/*.*").replace(/\/\*\.\*/,"")+(d?"":"/"));return j};f._hasResource={};return f})},"dojo/has":function(){define(["require"],function(a){var h=a.has||function(){},a=navigator.userAgent;h.add("dom-addeventlistener",
!!document.addEventListener);h.add("touch","ontouchstart"in document);h.add("device-width",screen.availWidth||innerWidth);h.add("agent-ios",!!a.match(/iPhone|iP[ao]d/));h.add("agent-android",a.indexOf("android")>1);h.clearElement=function(a){a.innerHTML="";return a};h.normalize=function(a,n){var e=a.match(/[\?:]|[^:\?]*/g),d=0,m=function(a){var k=e[d++];if(k==":")return 0;else{if(e[d++]=="?")return!a&&h(k)?m():(m(!0),m(a));return k||0}};return(a=m())&&n(a)};h.load=function(a,h,e){a?h([a],e):e()};
return h})},"dojo/_base/config":function(){define(["../has","require"],function(a,h){var l={},n=h.rawConfig,e;for(e in n)l[e]=n[e];return l})},"dojo/_base/sniff":function(){define(["./kernel","../has"],function(a,h){a.isBrowser=!0;a._name="browser";var l=h.add,n=navigator,e=n.userAgent,d=n.appVersion,m=parseFloat(d),f,k,b,o,j,s,p,c,g,i,q,u,r;e.indexOf("AdobeAIR")>=0&&(k=1);b=d.indexOf("Konqueror")>=0?m:0;o=parseFloat(e.split("WebKit/")[1])||void 0;j=parseFloat(e.split("Chrome/")[1])||void 0;s=d.indexOf("Macintosh")>=
0;u=/iPhone|iPod|iPad/.test(e);r=parseFloat(e.split("Android ")[1])||void 0;var t=Math.max(d.indexOf("WebKit"),d.indexOf("Safari"),0);if(t&&!j&&(p=parseFloat(d.split("Version/")[1]),!p||parseFloat(d.substr(t+7))<=419.3))p=2;if(!h("dojo-webkit")&&(e.indexOf("Opera")>=0&&(f=m,f>=9.8&&(f=parseFloat(e.split("Version/")[1])||m)),e.indexOf("Gecko")>=0&&!b&&!o&&(c=g=m),g&&(q=parseFloat(e.split("Firefox/")[1]||e.split("Minefield/")[1])||void 0),document.all&&!f))i=parseFloat(d.split("MSIE ")[1])||void 0,
(e=document.documentMode)&&e!=5&&Math.floor(i)!=e&&(i=e);e=document.compatMode=="BackCompat";l("opera",a.isOpera=f);l("air",a.isAIR=k);l("khtml",a.isKhtml=b);l("webkit",a.isWebKit=o);l("chrome",a.isChrome=j);l("mac",a.isMac=s);l("safari",a.isSafari=p);l("mozilla",a.isMozilla=a.isMoz=c);l("ie",a.isIE=i);l("ff",a.isFF=q);l("quirks",a.isQuirks=e);l("ios",a.isIos=u);l("android",a.isAndroid=r);a.locale=a.locale||(i?n.userLanguage:n.language).toLowerCase();return h})},"dojo/_base/lang":function(){define(["./kernel",
"../has","./sniff"],function(a,h){h.add("bug-for-in-skips-shadowed",function(){for(var a in{toString:1})return 0;return 1});var l=h("bug-for-in-skips-shadowed")?"hasOwnProperty.valueOf.isPrototypeOf.propertyIsEnumerable.toLocaleString.toString.constructor".split("."):[],n=l.length,e=function(a){a||(a={});for(var b=1,i=arguments.length;b<i;b++)p._mixin(a,arguments[b]);return a},d=function(c,b,i){var d,j=0,f=a.global;if(!i)if(c.length){d=c[j++];try{i=a.scopeMap[d]&&a.scopeMap[d][1]}catch(o){}i=i||(d in
f?f[d]:b?f[d]={}:void 0)}else return f;for(;i&&(d=c[j++]);)i=d in i?i[d]:b?i[d]={}:void 0;return i},m=function(a,b,i){return d(a.split("."),b,i)},f=Object.prototype.toString,k=function(){function a(){}return function(b,i){a.prototype=b;var d=new a;a.prototype=null;i&&p._mixin(d,i);return d}}(),b=function(a,b,i){return(i||[]).concat(Array.prototype.slice.call(a,b||0))},o=h("ie")?function(){function a(c,b,d){d=d||[];for(b=b||0;b<c.length;b++)d.push(c[b]);return d}return function(g){return(g.item?a:
b).apply(this,arguments)}}():b,j=function(a){if(!a||typeof a!="object"||p.isFunction(a))return a;if(a.nodeType&&"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return RegExp(a);var b,i,d;if(p.isArray(a)){b=[];i=0;for(d=a.length;i<d;++i)i in a&&b.push(j(a[i]))}else b=a.constructor?new a.constructor:{};return p._mixin(b,a,j)},s=/\{([^\}]+)\}/g,p={_extraNames:l,_mixin:function(a,b,i){var d,j,f,o={};for(d in b)if(j=b[d],!(d in a)||a[d]!==
j&&(!(d in o)||o[d]!==j))a[d]=i?i(j):j;if(h("bug-for-in-skips-shadowed")&&b)for(f=0;f<n;++f)if(d=l[f],j=b[d],!(d in a)||a[d]!==j&&(!(d in o)||o[d]!==j))a[d]=i?i(j):j;return a},mixin:e,setObject:function(a,b,i){var j=a.split("."),a=j.pop();return(i=d(j,!0,i))&&a?i[a]=b:void 0},getObject:m,exists:function(a,b){return p.getObject(a,!1,b)!==void 0},isString:function(a){return typeof a=="string"||a instanceof String},isArray:function(a){return a&&(a instanceof Array||typeof a=="array")},isFunction:function(a){return f.call(a)===
"[object Function]"},isObject:function(a){return a!==void 0&&(a===null||typeof a=="object"||p.isArray(a)||p.isFunction(a))},isArrayLike:function(a){return a&&a!==void 0&&!p.isString(a)&&!p.isFunction(a)&&!(a.tagName&&a.tagName.toLowerCase()=="form")&&(p.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&!p.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(String(a))},extend:function(a){for(var b=1,d=arguments.length;b<d;b++)p._mixin(a.prototype,arguments[b]);return a},_hitchArgs:function(b,
g){var d=o(arguments,2),j=p.isString(g);return function(){var f=o(arguments),e=j?(b||a.global)[g]:g;return e&&e.apply(b||this,d.concat(f))}},hitch:function(b,g){if(arguments.length>2)return p._hitchArgs.apply(a,arguments);g||(g=b,b=null);if(p.isString(g)){b=b||a.global;if(!b[g])throw['dojo.hitch: scope["',g,'"] is null (scope="',b,'")'].join("");return function(){return b[g].apply(b,arguments||[])}}return!b?g:function(){return g.apply(b,arguments||[])}},delegate:k,_toArray:o,partial:function(){return p.hitch.apply(a,
[null].concat(p._toArray(arguments)))},clone:j,trim:String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(a,b,d){return a.replace(d||s,p.isFunction(b)?b:function(a,c){return m(c,!1,b)})}};e(a,p);return p})},"dojo/_base/array":function(){define(["./kernel","../has","./lang"],function(a,h,l){function n(a){return m[a]=new Function("item","index","array",a)}function e(a){var d=!a;return function(j,f,e){var c=0,g=j&&j.length||
0,i;g&&typeof j=="string"&&(j=j.split(""));typeof f=="string"&&(f=m[f]||n(f));if(e)for(;c<g;++c){if(i=!f.call(e,j[c],c,j),a^i)return!i}else for(;c<g;++c)if(i=!f(j[c],c,j),a^i)return!i;return d}}function d(a){var d=1,j=0,e=0;a||(d=j=e=-1);return function(p,c,g,i){if(i&&d>0)return k.lastIndexOf(p,c,g);var i=p&&p.length||0,m=a?i+e:j;g===f?g=a?j:i+e:g<0?(g=i+g,g<0&&(g=j)):g=g>=i?i+e:g;for(i&&typeof p=="string"&&(p=p.split(""));g!=m;g+=d)if(p[g]==c)return g;return-1}}var m={},f,k;k={every:e(!1),some:e(!0),
indexOf:d(!0),lastIndexOf:d(!1),forEach:function(a,d,j){var f=0,e=a&&a.length||0;e&&typeof a=="string"&&(a=a.split(""));typeof d=="string"&&(d=m[d]||n(d));if(j)for(;f<e;++f)d.call(j,a[f],f,a);else for(;f<e;++f)d(a[f],f,a)},map:function(a,d,j,f){var e=0,c=a&&a.length||0,f=new (f||Array)(c);c&&typeof a=="string"&&(a=a.split(""));typeof d=="string"&&(d=m[d]||n(d));if(j)for(;e<c;++e)f[e]=d.call(j,a[e],e,a);else for(;e<c;++e)f[e]=d(a[e],e,a);return f},filter:function(a,d,j){var f=0,e=a&&a.length||0,c=
[],g;e&&typeof a=="string"&&(a=a.split(""));typeof d=="string"&&(d=m[d]||n(d));if(j)for(;f<e;++f)g=a[f],d.call(j,g,f,a)&&c.push(g);else for(;f<e;++f)g=a[f],d(g,f,a)&&c.push(g);return c},clearCache:function(){m={}}};l.mixin(a,k);return k})},"dojo/ready":function(){define(["./_base/kernel","./has","require","./domReady","./_base/lang"],function(a,h,l,n,e){var d=0,m,f=[],k=0,b=function(){if(d&&!k&&f.length){k=1;var a=f.shift();try{a()}finally{k=0}k=0;f.length&&m(b)}};l.on("idle",b);m=function(){l.idle()&&
b()};var h=a.ready=a.addOnLoad=function(b,d,o){var c=e._toArray(arguments);typeof b!="number"?(o=d,d=b,b=1E3):c.shift();o=o?e.hitch.apply(a,c):function(){d()};o.priority=b;for(c=0;c<f.length&&b>=f[c].priority;c++);f.splice(c,0,o);m()},o=a.config.addOnLoad;if(o)h[e.isArray(o)?"apply":"call"](a,o);a.config.parseOnLoad&&!a.isAsync&&h(99,function(){a.parser||(a.deprecated("Add explicit require(['dojo/parser']);","","2.0"),l(["dojo/parser"]))});n(function(){d=1;a._postLoad=a.config.afterOnLoad=!0;f.length&&
m(b)});return h})},"dojo/domReady":function(){define(["./has"],function(a){function h(a){m?a(1):f.push(a)}var l=this,n=document,e={loaded:1,complete:1},d=typeof n.readyState!="string",m=!!e[n.readyState];if(d)n.readyState="loading";if(!m){var f=[],k=[],b=function(a){a=a||l.event;if(!(m||a.type=="readystatechange"&&!e[n.readyState])){m=1;if(d)n.readyState="complete";for(;f.length;)f.shift()()}},o=function(a,d){a.addEventListener(d,b,!1);f.push(function(){a.removeEventListener(d,b,!1)})};if(!a("dom-addeventlistener")){var o=
function(a,d){d="on"+d;a.attachEvent(d,b);f.push(function(){a.detachEvent(d,b)})},j=n.createElement("div");try{j.doScroll&&l.frameElement===null&&k.push(function(){try{return j.doScroll("left"),1}catch(a){}})}catch(s){}}o(n,"DOMContentLoaded");o(l,"load");"onreadystatechange"in n?o(n,"readystatechange"):d||k.push(function(){return e[n.readyState]});if(k.length){var p=function(){if(!m){for(var a=k.length;a--;)if(k[a]()){b("poller");return}setTimeout(p,30)}};p()}}h.load=function(a,b,d){h(d)};return h})},
"dojo/_base/declare":function(){define(["./kernel","../has","./lang"],function(a,h,l){function n(a,b){throw Error("declare"+(b?" "+b:"")+": "+a);}function e(a,b,c){var d,g,i,f,j,e,o,k=this._inherited=this._inherited||{};typeof a=="string"&&(d=a,a=b,b=c);c=0;f=a.callee;(d=d||f.nom)||n("can't deduce a name to call inherited()",this.declaredClass);j=this.constructor._meta;i=j.bases;o=k.p;if(d!=w){if(k.c!==f&&(o=0,e=i[0],j=e._meta,j.hidden[d]!==f)){(g=j.chains)&&typeof g[d]=="string"&&n("calling chained method with inherited: "+
d,this.declaredClass);do if(j=e._meta,g=e.prototype,j&&(g[d]===f&&g.hasOwnProperty(d)||j.hidden[d]===f))break;while(e=i[++o]);o=e?o:-1}if(e=i[++o])if(g=e.prototype,e._meta&&g.hasOwnProperty(d))c=g[d];else{f=u[d];do if(g=e.prototype,(c=g[d])&&(e._meta?g.hasOwnProperty(d):c!==f))break;while(e=i[++o])}c=e&&c||u[d]}else{if(k.c!==f&&(o=0,(j=i[0]._meta)&&j.ctor!==f)){g=j.chains;for((!g||g.constructor!=="manual")&&n("calling chained constructor with inherited",this.declaredClass);e=i[++o];)if((j=e._meta)&&
j.ctor===f)break;o=e?o:-1}for(;e=i[++o];)if(c=(j=e._meta)?j.ctor:e)break;c=e&&c}k.c=c;k.p=o;if(c)return b===!0?c:c.apply(this,b||a)}function d(a,b){if(typeof a=="string")return this.__inherited(a,b,!0);return this.__inherited(a,!0)}function m(a,b,c){var d=this.getInherited(a,b);if(d)return d.apply(this,c||b||a)}function f(a){for(var b=this.constructor._meta.bases,c=0,d=b.length;c<d;++c)if(b[c]===a)return!0;return this instanceof a}function k(a,b){for(var c in b)c!=w&&b.hasOwnProperty(c)&&(a[c]=b[c]);
if(h("bug-for-in-skips-shadowed"))for(var d=l._extraNames,g=d.length;g;)c=d[--g],c!=w&&b.hasOwnProperty(c)&&(a[c]=b[c])}function b(a){i.safeMixin(this.prototype,a);return this}function o(a,b){return function(){var v;var c=arguments,d=c,i=c[0],f,j;j=a.length;var e;if(!(this instanceof c.callee))return g(c);if(b&&(i&&i.preamble||this.preamble)){e=Array(a.length);e[0]=c;for(f=0;;){if(i=c[0])(i=i.preamble)&&(c=i.apply(this,c)||c);i=a[f].prototype;(i=i.hasOwnProperty("preamble")&&i.preamble)&&(c=i.apply(this,
c)||c);if(++f==j)break;e[f]=c}}for(f=j-1;f>=0;--f)i=a[f],(v=(j=i._meta)?j.ctor:i,i=v)&&i.apply(this,e?e[f]:c);(i=this.postscript)&&i.apply(this,d)}}function j(a,b){return function(){var c=arguments,d=c,i=c[0];if(!(this instanceof c.callee))return g(c);if(b){if(i)(i=i.preamble)&&(d=i.apply(this,d)||d);(i=this.preamble)&&i.apply(this,d)}a&&a.apply(this,c);(i=this.postscript)&&i.apply(this,c)}}function s(a){return function(){var v;var b=arguments,c=0,d,i;if(!(this instanceof b.callee))return g(b);for(;d=
a[c];++c)if(v=(i=d._meta)?i.ctor:d,d=v){d.apply(this,b);break}(d=this.postscript)&&d.apply(this,b)}}function p(a,b,c){return function(){var d,g,i=0,f=1;c&&(i=b.length-1,f=-1);for(;d=b[i];i+=f)g=d._meta,(d=(g?g.hidden:d.prototype)[a])&&d.apply(this,arguments)}}function c(a){t.prototype=a.prototype;a=new t;t.prototype=null;return a}function g(a){var b=a.callee,d=c(b);b.apply(d,a);return d}function i(a,g,m){typeof a!="string"&&(m=g,g=a,a="");var m=m||{},h,t,v,B,F,C,E,G=1,K=g;if(r.call(g)=="[object Array]"){G=
a;v=[];B=[{cls:0,refs:[]}];C={};for(var V=1,W=g.length,L=0,z,M,y,H;L<W;++L){(z=g[L])?r.call(z)!="[object Function]"&&n("mixin #"+L+" is not a callable constructor.",G):n("mixin #"+L+" is unknown. Did you use dojo.require to pull it in?",G);M=z._meta?z._meta.bases:[z];y=0;for(z=M.length-1;z>=0;--z){H=M[z].prototype;if(!H.hasOwnProperty("declaredClass"))H.declaredClass="uniqName_"+A++;H=H.declaredClass;C.hasOwnProperty(H)||(C[H]={count:0,refs:[],cls:M[z]},++V);H=C[H];y&&y!==H&&(H.refs.push(y),++y.count);
y=H}++y.count;B[0].refs.push(y)}for(;B.length;){y=B.pop();v.push(y.cls);for(--V;t=y.refs,t.length==1;){y=t[0];if(!y||--y.count){y=0;break}v.push(y.cls);--V}if(y){L=0;for(W=t.length;L<W;++L)y=t[L],--y.count||B.push(y)}}V&&n("can't build consistent linearization",G);z=g[0];v[0]=z?z._meta&&z===v[v.length-z._meta.bases.length]?z._meta.bases.length:1:0;C=v;v=C[0];G=C.length-v;g=C[G]}else C=[0],g?r.call(g)=="[object Function]"?(v=g._meta,C=C.concat(v?v.bases:g)):n("base class is not a callable constructor.",
a):g!==null&&n("unknown base class. Did you use dojo.require to pull it in?",a);if(g)for(t=G-1;;--t){h=c(g);if(!t)break;v=C[t];(v._meta?k:q)(h,v.prototype);B=new Function;B.superclass=g;B.prototype=h;g=h.constructor=B}else h={};i.safeMixin(h,m);v=m.constructor;if(v!==u.constructor)v.nom=w,h.constructor=v;for(t=G-1;t;--t)(v=C[t]._meta)&&v.chains&&(E=q(E||{},v.chains));h["-chains-"]&&(E=q(E||{},h["-chains-"]));v=!E||!E.hasOwnProperty(w);C[0]=B=E&&E.constructor==="manual"?s(C):C.length==1?j(m.constructor,
v):o(C,v);B._meta={bases:C,hidden:m,chains:E,parents:K,ctor:m.constructor};B.superclass=g&&g.prototype;B.extend=b;B.prototype=h;h.constructor=B;h.getInherited=d;h.isInstanceOf=f;h.inherited=I;h.__inherited=e;if(a)h.declaredClass=a,l.setObject(a,B);if(E)for(F in E)if(h[F]&&typeof E[F]=="string"&&F!=w)v=h[F]=p(F,C,E[F]==="after"),v.nom=F;return B}var q=l.mixin,u=Object.prototype,r=u.toString,t=new Function,A=0,w="constructor",I=a.config.isDebug?m:e;a.safeMixin=i.safeMixin=function(a,b){var c,d;for(c in b)if(d=
b[c],(d!==u[c]||!(c in u))&&c!=w){if(r.call(d)=="[object Function]")d.nom=c;a[c]=d}if(h("bug-for-in-skips-shadowed"))for(var g=l._extraNames,i=g.length;i;)if(c=g[--i],d=b[c],(d!==u[c]||!(c in u))&&c!=w){if(r.call(d)=="[object Function]")d.nom=c;a[c]=d}return a};return a.declare=i})},"dojo/_base/connect":function(){define(["./kernel","../on","../topic","../aspect","./event","../mouse","./sniff","./lang","../keys"],function(a,h,l,n,e,d,m,f){function k(b,c,j,e,o){e=f.hitch(j,e);if(!b||!b.addEventListener&&
!b.attachEvent)return n.after(b||a.global,c,e,!0);typeof c=="string"&&c.substring(0,2)=="on"&&(c=c.substring(2));if(!b)b=a.global;if(!o)switch(c){case "keypress":c=p;break;case "mouseenter":c=d.enter;break;case "mouseleave":c=d.leave}return h(b,c,e,o)}function b(a){a.keyChar=a.charCode?String.fromCharCode(a.charCode):"";a.charOrCode=a.keyChar||a.keyCode}m.add("events-keypress-typed",function(){var a={charCode:0};try{a=document.createEvent("KeyboardEvent"),(a.initKeyboardEvent||a.initKeyEvent).call(a,
"keypress",!0,!0,null,!1,!1,!1,!1,9,3)}catch(b){}return a.charCode==0&&!m("opera")});var o={106:42,111:47,186:59,187:43,188:44,189:45,190:46,191:47,192:96,219:91,220:92,221:93,222:39,229:113},j=m("mac")?"metaKey":"ctrlKey",s=function(a,c){var d=f.mixin({},a,c);b(d);d.preventDefault=function(){a.preventDefault()};d.stopPropagation=function(){a.stopPropagation()};return d},p;p=m("events-keypress-typed")?function(a,b){var c=h(a,"keydown",function(a){var c=a.keyCode,d=(c!=13||m("ie")>=9&&!m("quirks"))&&
c!=32&&(c!=27||!m("ie"))&&(c<48||c>90)&&(c<96||c>111)&&(c<186||c>192)&&(c<219||c>222)&&c!=229;if(d||a.ctrlKey){d=d?0:c;if(a.ctrlKey)if(c==3||c==13)return b.call(a.currentTarget,a);else d>95&&d<106?d-=48:!a.shiftKey&&d>=65&&d<=90?d+=32:d=o[d]||d;c=s(a,{type:"keypress",faux:!0,charCode:d});b.call(a.currentTarget,c);if(m("ie"))try{a.keyCode=c.keyCode}catch(g){}}}),d=h(a,"keypress",function(a){var c=a.charCode,a=s(a,{charCode:c>=32?c:0,faux:!0});return b.call(this,a)});return{remove:function(){c.remove();
d.remove()}}}:m("opera")?function(a,b){return h(a,"keypress",function(a){var c=a.which;c==3&&(c=99);c=c<32&&!a.shiftKey?0:c;a.ctrlKey&&!a.shiftKey&&c>=65&&c<=90&&(c+=32);return b.call(this,s(a,{charCode:c}))})}:function(a,c){return h(a,"keypress",function(a){b(a);return c.call(this,a)})};var c={_keypress:p,connect:function(){var a=arguments,b=[],c=0;b.push(typeof a[0]=="string"?null:a[c++],a[c++]);var d=a[c+1];b.push(typeof d=="string"||typeof d=="function"?a[c++]:null,a[c++]);for(d=a.length;c<d;c++)b.push(a[c]);
return k.apply(this,b)},disconnect:function(a){a&&a.remove()},subscribe:function(a,b,c){return l.subscribe(a,f.hitch(b,c))},publish:function(a,b){return l.publish.apply(l,[a].concat(b))},connectPublisher:function(a,b,d){var f=function(){c.publish(a,arguments)};return d?c.connect(b,d,f):c.connect(b,f)},isCopyKey:function(a){return a[j]}};c.unsubscribe=c.disconnect;f.mixin(a,c);return c})},"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect","./_base/kernel","./has"],function(a,h,l){function n(a,
b,d,g,i){if(g=b.match(/(.*):(.*)/))return b=g[2],g=g[1],f.selector(g,b).call(i,a,d);l("touch")&&(k.test(b)&&(d=r(d)),!l("event-orientationchange")&&b=="orientationchange"&&(b="resize",a=window,d=r(d)));if(a.addEventListener){var e=b in j;a.addEventListener(e?j[b]:b,d,e);return{remove:function(){a.removeEventListener(b,d,e)}}}b="on"+b;if(c&&a.attachEvent)return c(a,b,d);throw Error("Target must be an event emitter");}function e(){this.cancelable=!1}function d(){this.bubbles=!1}var m=window.ScriptEngineMajorVersion;
l.add("jscript",m&&m()+ScriptEngineMinorVersion()/10);l.add("event-orientationchange",l("touch")&&!l("android"));var f=function(a,b,c,d){if(a.on)return a.on(b,c);return f.parse(a,b,c,n,d,this)};f.pausable=function(a,b,c,d){var g,a=f(a,b,function(){if(!g)return c.apply(this,arguments)},d);a.pause=function(){g=!0};a.resume=function(){g=!1};return a};f.once=function(a,b,c){var d=f(a,b,function(){d.remove();return c.apply(this,arguments)});return d};f.parse=function(a,b,c,d,g,i){if(b.call)return b.call(i,
a,c);if(b.indexOf(",")>-1){for(var b=b.split(/\s*,\s*/),f=[],j=0,e;e=b[j++];)f.push(d(a,e,c,g,i));f.remove=function(){for(var a=0;a<f.length;a++)f[a].remove()};return f}return d(a,b,c,g,i)};var k=/^touch/;f.selector=function(a,b,c){return function(d,g){var i=this,j=b.bubble;j?b=j:c!==!1&&(c=!0);return f(d,b,function(b){var f=b.target;for(i=i&&i.matches?i:h.query;!i.matches(f,a,d);)if(f==d||!c||!(f=f.parentNode))return;return g.call(f,b)})}};var b=[].slice,o=f.emit=function(a,c,g){var i=b.call(arguments,
2),f="on"+c;if("parentNode"in a){var j=i[0]={},o;for(o in g)j[o]=g[o];j.preventDefault=e;j.stopPropagation=d;j.target=a;j.type=c;g=j}do a[f]&&a[f].apply(a,i);while(g&&g.bubbles&&(a=a.parentNode));return g&&g.cancelable&&g},j={};if(l("dom-addeventlistener")){j={focusin:"focus",focusout:"blur"};if(l("opera"))j.keydown="keypress";f.emit=function(a,b,c){if(a.dispatchEvent&&document.createEvent){var d=document.createEvent("HTMLEvents");d.initEvent(b,!!c.bubbles,!!c.cancelable);for(var g in c)g in d||(d[g]=
c[g]);return a.dispatchEvent(d)&&d}return o.apply(f,arguments)}}else{f._fixEvent=function(a,b){if(!a)a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event;if(!a)return a;if(!a.target){a.target=a.srcElement;a.currentTarget=b||a.srcElement;if(a.type=="mouseover")a.relatedTarget=a.fromElement;if(a.type=="mouseout")a.relatedTarget=a.toElement;if(!a.stopPropagation)a.stopPropagation=g,a.preventDefault=i;switch(a.type){case "keypress":var c="charCode"in a?a.charCode:a.keyCode;c==10?(c=0,a.keyCode=
13):c==13||c==27?c=0:c==3&&(c=99);a.charCode=c;c=a;c.keyChar=c.charCode?String.fromCharCode(c.charCode):"";c.charOrCode=c.keyChar||c.keyCode}}return a};var s=function(a){this.handle=a};s.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var p=function(a){return function(b){b=f._fixEvent(b,this);return a.call(this,b)}},c=function(b,c,d){d=p(d);if(((b.ownerDocument?b.ownerDocument.parentWindow:b.parentWindow||b.window||window)!=top||l("jscript")<5.8)&&!l("config-_allow_leaks")){typeof _dojoIEListeners_==
"undefined"&&(_dojoIEListeners_=[]);var g=b[c];if(!g||!g.listeners){var i=g;b[c]=g=Function("event","var callee = arguments.callee; for(var i = 0; i<callee.listeners.length; i++){var listener = _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");g.listeners=[];g.global=this;i&&g.listeners.push(_dojoIEListeners_.push(i)-1)}g.listeners.push(b=g.global._dojoIEListeners_.push(d)-1);return new s(b)}return a.after(b,c,d,!0)},g=function(){this.cancelBubble=!0},i=f._preventDefault=
function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.returnValue=!1}}if(l("touch"))var q=function(){},u=window.orientation,r=function(a){return function(b){var c=b.corrected;if(!c){var d=b.type;try{delete b.type}catch(g){}b.type?(q.prototype=b,c=new q,c.preventDefault=function(){b.preventDefault()},c.stopPropagation=function(){b.stopPropagation()}):(c=b,c.type=d);b.corrected=c;if(d=="resize"){if(u==window.orientation)return null;u=window.orientation;c.type=
"orientationchange";return a.call(this,c)}if(!("rotation"in c))c.rotation=0,c.scale=1;var d=c.changedTouches[0],i;for(i in d)delete c[i],c[i]=d[i]}return a.call(this,c)}};return f})},"dojo/topic":function(){define(["./Evented"],function(a){var h=new a;return{publish:function(){return h.emit.apply(h,arguments)},subscribe:function(){return h.on.apply(h,arguments)}}})},"dojo/Evented":function(){define("dojo/Evented",["./aspect","./on"],function(a,h){function l(){}var n=a.after;l.prototype={on:function(a,
d){return h.parse(this,a,d,function(a,f){return n(a,"on"+f,d,!0)})},emit:function(){var a=[this];a.push.apply(a,arguments);return h.emit.apply(h,a)}};return l})},"dojo/aspect":function(){define("dojo/aspect",[],function(){function a(a,e,d,m){var f=a[e],k=e=="around",b;if(k){var o=d(function(){return f.advice(this,arguments)});b={remove:function(){b.cancelled=!0},advice:function(a,d){return b.cancelled?f.advice(a,d):o.apply(a,d)}}}else b={remove:function(){var d=b.previous,f=b.next;if(!f&&!d)delete a[e];
else if(d?d.next=f:a[e]=f,f)f.previous=d},id:l++,advice:d,receiveArguments:m};if(f&&!k)if(e=="after"){for(d=f;d;)f=d,d=d.next;f.next=b;b.previous=f}else{if(e=="before")a[e]=b,b.next=f,f.previous=b}else a[e]=b;return b}function h(h){return function(e,d,m,f){var k=e[d],b;if(!k||k.target!=e){e[d]=b=function(){for(var a=l,d=arguments,f=b.before;f;)d=f.advice.apply(this,d)||d,f=f.next;if(b.around)var e=b.around.advice(this,d);for(f=b.after;f&&f.id<a;)e=f.receiveArguments?f.advice.apply(this,d)||e:f.advice.call(this,
e),f=f.next;return e};if(k)b.around={advice:function(a,b){return k.apply(a,b)}};b.target=e}e=a(b||k,h,m,f);m=null;return e}}var l=0;return{before:h("before"),around:h("around"),after:h("after")}})},"dojo/_base/event":function(){define(["./kernel","../on","../has","../dom-geometry"],function(a,h,l,n){if(h._fixEvent){var e=h._fixEvent;h._fixEvent=function(a,h){(a=e(a,h))&&n.normalizeEvent(a);return a}}a.fixEvent=function(a,e){if(h._fixEvent)return h._fixEvent(a,e);return a};a.stopEvent=function(a){l("dom-addeventlistener")||
a&&a.preventDefault?(a.preventDefault(),a.stopPropagation()):(a=a||window.event,a.cancelBubble=!0,h._preventDefault.call(a))};return{fix:a.fixEvent,stop:a.stopEvent}})},"dojo/dom-geometry":function(){define(["./_base/sniff","./_base/window","./dom","./dom-style"],function(a,h,l,n){function e(a,d,f,e,k,c){c=c||"px";a=a.style;if(!isNaN(d))a.left=d+c;if(!isNaN(f))a.top=f+c;if(e>=0)a.width=e+c;if(k>=0)a.height=k+c}function d(a){return a.tagName.toLowerCase()=="button"||a.tagName.toLowerCase()=="input"&&
(a.getAttribute("type")||"").toLowerCase()=="button"}function m(a){return f.boxModel=="border-box"||a.tagName.toLowerCase()=="table"||d(a)}var f={boxModel:"content-box"};if(a("ie"))f.boxModel=document.compatMode=="BackCompat"?"border-box":"content-box";f.getPadExtents=function(a,d){var a=l.byId(a),f=d||n.getComputedStyle(a),e=n.toPixelValue,k=e(a,f.paddingLeft),c=e(a,f.paddingTop),g=e(a,f.paddingRight),f=e(a,f.paddingBottom);return{l:k,t:c,r:g,b:f,w:k+g,h:c+f}};f.getBorderExtents=function(a,d){var a=
l.byId(a),f=n.toPixelValue,e=d||n.getComputedStyle(a),k=e.borderLeftStyle!="none"?f(a,e.borderLeftWidth):0,c=e.borderTopStyle!="none"?f(a,e.borderTopWidth):0,g=e.borderRightStyle!="none"?f(a,e.borderRightWidth):0,f=e.borderBottomStyle!="none"?f(a,e.borderBottomWidth):0;return{l:k,t:c,r:g,b:f,w:k+g,h:c+f}};f.getPadBorderExtents=function(a,d){var a=l.byId(a),e=d||n.getComputedStyle(a),k=f.getPadExtents(a,e),e=f.getBorderExtents(a,e);return{l:k.l+e.l,t:k.t+e.t,r:k.r+e.r,b:k.b+e.b,w:k.w+e.w,h:k.h+e.h}};
f.getMarginExtents=function(b,d){var b=l.byId(b),f=d||n.getComputedStyle(b),e=n.toPixelValue,k=e(b,f.marginLeft),c=e(b,f.marginTop),g=e(b,f.marginRight),e=e(b,f.marginBottom);a("webkit")&&f.position!="absolute"&&(g=k);return{l:k,t:c,r:g,b:e,w:k+g,h:c+e}};f.getMarginBox=function(b,d){var b=l.byId(b),e=d||n.getComputedStyle(b),k=f.getMarginExtents(b,e),h=b.offsetLeft-k.l,c=b.offsetTop-k.t,g=b.parentNode,i=n.toPixelValue;if(a("mozilla")){var m=parseFloat(e.left),e=parseFloat(e.top);!isNaN(m)&&!isNaN(e)?
(h=m,c=e):g&&g.style&&(g=n.getComputedStyle(g),g.overflow!="visible"&&(h+=g.borderLeftStyle!="none"?i(b,g.borderLeftWidth):0,c+=g.borderTopStyle!="none"?i(b,g.borderTopWidth):0))}else if((a("opera")||a("ie")==8&&!a("quirks"))&&g)g=n.getComputedStyle(g),h-=g.borderLeftStyle!="none"?i(b,g.borderLeftWidth):0,c-=g.borderTopStyle!="none"?i(b,g.borderTopWidth):0;return{l:h,t:c,w:b.offsetWidth+k.w,h:b.offsetHeight+k.h}};f.getContentBox=function(b,d){var b=l.byId(b),e=d||n.getComputedStyle(b),k=b.clientWidth,
h=f.getPadExtents(b,e),c=f.getBorderExtents(b,e);k?(e=b.clientHeight,c.w=c.h=0):(k=b.offsetWidth,e=b.offsetHeight);a("opera")&&(h.l+=c.l,h.t+=c.t);return{l:h.l,t:h.t,w:k-h.w-c.w,h:e-h.h-c.h}};f.setContentSize=function(a,d,j){var a=l.byId(a),k=d.w,d=d.h;m(a)&&(j=f.getPadBorderExtents(a,j),k>=0&&(k+=j.w),d>=0&&(d+=j.h));e(a,NaN,NaN,k,d)};var k={l:0,t:0,w:0,h:0};f.setMarginBox=function(b,o,j){var b=l.byId(b),h=j||n.getComputedStyle(b),j=o.w,p=o.h,c=m(b)?k:f.getPadBorderExtents(b,h),h=f.getMarginExtents(b,
h);if(a("webkit")&&d(b)){var g=b.style;if(j>=0&&!g.width)g.width="4px";if(p>=0&&!g.height)g.height="4px"}j>=0&&(j=Math.max(j-c.w-h.w,0));p>=0&&(p=Math.max(p-c.h-h.h,0));e(b,o.l,o.t,j,p)};f.isBodyLtr=function(){return(h.body().dir||h.doc.documentElement.dir||"ltr").toLowerCase()=="ltr"};f.docScroll=function(){var b=h.doc.parentWindow||h.doc.defaultView;return"pageXOffset"in b?{x:b.pageXOffset,y:b.pageYOffset}:(b=a("quirks")?h.body():h.doc.documentElement,{x:f.fixIeBiDiScrollLeft(b.scrollLeft||0),y:b.scrollTop||
0})};f.getIeDocumentElementOffset=function(){var b=h.doc.documentElement;if(a("ie")<8){var d=b.getBoundingClientRect(),f=d.left,d=d.top;a("ie")<7&&(f+=b.clientLeft,d+=b.clientTop);return{x:f<0?0:f,y:d<0?0:d}}else return{x:0,y:0}};f.fixIeBiDiScrollLeft=function(b){var d=a("ie");if(d&&!f.isBodyLtr()){var e=a("quirks"),k=e?h.body():h.doc.documentElement;d==6&&!e&&h.global.frameElement&&k.scrollHeight>k.clientHeight&&(b+=k.clientLeft);return d<8||e?b+k.clientWidth-k.scrollWidth:-b}return b};f.position=
function(b,d){var b=l.byId(b),e=h.body(),k=e.parentNode,m=b.getBoundingClientRect(),m={x:m.left,y:m.top,w:m.right-m.left,h:m.bottom-m.top};if(a("ie"))k=f.getIeDocumentElementOffset(),m.x-=k.x+(a("quirks")?e.clientLeft+e.offsetLeft:0),m.y-=k.y+(a("quirks")?e.clientTop+e.offsetTop:0);else if(a("ff")==3){var e=n.getComputedStyle(k),c=n.toPixelValue;m.x-=c(k,e.marginLeft)+c(k,e.borderLeftWidth);m.y-=c(k,e.marginTop)+c(k,e.borderTopWidth)}d&&(k=f.docScroll(),m.x+=k.x,m.y+=k.y);return m};f.getMarginSize=
function(a,d){var a=l.byId(a),e=f.getMarginExtents(a,d||n.getComputedStyle(a)),k=a.getBoundingClientRect();return{w:k.right-k.left+e.w,h:k.bottom-k.top+e.h}};f.normalizeEvent=function(b){if(!("layerX"in b))b.layerX=b.offsetX,b.layerY=b.offsetY;if(!a("dom-addeventlistener")){var d=b.target,d=d&&d.ownerDocument||document,d=a("quirks")?d.body:d.documentElement,e=f.getIeDocumentElementOffset();b.pageX=b.clientX+f.fixIeBiDiScrollLeft(d.scrollLeft||0)-e.x;b.pageY=b.clientY+(d.scrollTop||0)-e.y}};return f})},
"dojo/_base/window":function(){define(["./kernel","../has","./sniff"],function(a,h){a.doc=this.document||null;a.body=function(){return a.doc.body||a.doc.getElementsByTagName("body")[0]};a.setContext=function(h,e){a.global=l.global=h;a.doc=l.doc=e};a.withGlobal=function(h,e,d,m){var f=a.global;try{return a.global=l.global=h,a.withDoc.call(null,h.document,e,d,m)}finally{a.global=l.global=f}};a.withDoc=function(n,e,d,m){var f=a.doc,k=a.isQuirks,b=a.isIE,o,j,s;try{a.doc=l.doc=n;a.isQuirks=h.add("quirks",
a.doc.compatMode=="BackCompat",!0,!0);if(h("ie")&&(s=n.parentWindow)&&s.navigator)o=parseFloat(s.navigator.appVersion.split("MSIE ")[1])||void 0,(j=n.documentMode)&&j!=5&&Math.floor(o)!=j&&(o=j),a.isIE=h.add("ie",o,!0,!0);d&&typeof e=="string"&&(e=d[e]);return e.apply(d,m||[])}finally{a.doc=l.doc=f,a.isQuirks=h.add("quirks",k,!0,!0),a.isIE=h.add("ie",b,!0,!0)}};var l={global:a.global,doc:a.doc,body:a.body,setContext:a.setContext,withGlobal:a.withGlobal,withDoc:a.withDoc};return l})},"dojo/dom":function(){define(["./_base/sniff",
"./_base/lang","./_base/window"],function(a,h,l){try{document.execCommand("BackgroundImageCache",!1,!0)}catch(n){}var e={};e.byId=a("ie")?function(a,e){if(typeof a!="string")return a;var f=e||l.doc,k=a&&f.getElementById(a);if(k&&(k.attributes.id.value==a||k.id==a))return k;else{f=f.all[a];if(!f||f.nodeName)f=[f];for(var b=0;k=f[b++];)if(k.attributes&&k.attributes.id&&k.attributes.id.value==a||k.id==a)return k}}:function(a,e){return(typeof a=="string"?(e||l.doc).getElementById(a):a)||null};e.isDescendant=
function(a,h){try{a=e.byId(a);for(h=e.byId(h);a;){if(a==h)return!0;a=a.parentNode}}catch(f){}return!1};e.setSelectable=function(d,h){d=e.byId(d);if(a("mozilla"))d.style.MozUserSelect=h?"":"none";else if(a("khtml")||a("webkit"))d.style.KhtmlUserSelect=h?"auto":"none";else if(a("ie"))for(var f=d.unselectable=h?"":"on",k=d.getElementsByTagName("*"),b=0,o=k.length;b<o;++b)k.item(b).unselectable=f};return e})},"dojo/dom-style":function(){define(["./_base/sniff","./dom"],function(a,h){function l(f,c,g){c=
c.toLowerCase();if(a("ie")){if(g=="auto"){if(c=="height")return f.offsetHeight;if(c=="width")return f.offsetWidth}if(c=="fontweight")switch(g){case 700:return"bold";default:return"normal"}}c in b||(b[c]=o.test(c));return b[c]?d(f,g):g}var n,e={};n=a("webkit")?function(a){var c;if(a.nodeType==1){var b=a.ownerDocument.defaultView;c=b.getComputedStyle(a,null);if(!c&&a.style)a.style.display="",c=b.getComputedStyle(a,null)}return c||{}}:a("ie")&&(a("ie")<9||a("quirks"))?function(a){return a.nodeType==
1?a.currentStyle:{}}:function(a){return a.nodeType==1?a.ownerDocument.defaultView.getComputedStyle(a,null):{}};e.getComputedStyle=n;var d;d=a("ie")?function(a,c){if(!c)return 0;if(c=="medium")return 4;if(c.slice&&c.slice(-2)=="px")return parseFloat(c);var b=a.style,d=a.runtimeStyle,f=b.left,e=d.left;d.left=a.currentStyle.left;try{b.left=c,c=b.pixelLeft}catch(k){c=0}b.left=f;d.left=e;return c}:function(a,c){return parseFloat(c)||0};e.toPixelValue=d;var m=function(a,c){try{return a.filters.item("DXImageTransform.Microsoft.Alpha")}catch(b){return c?
{}:null}},f=a("ie")<9||a("ie")&&a("quirks")?function(a){try{return m(a).Opacity/100}catch(c){return 1}}:function(a){return n(a).opacity},k=a("ie")<9||a("ie")&&a("quirks")?function(a,c){var b=c*100,d=c==1;a.style.zoom=d?"":1;if(m(a))m(a,1).Opacity=b;else{if(d)return c;a.style.filter+=" progid:DXImageTransform.Microsoft.Alpha(Opacity="+b+")"}m(a,1).Enabled=!d;if(a.tagName.toLowerCase()=="tr")for(b=a.firstChild;b;b=b.nextSibling)b.tagName.toLowerCase()=="td"&&k(b,c);return c}:function(a,c){return a.style.opacity=
c},b={left:!0,top:!0},o=/margin|padding|width|height|max|min|offset/,j=a("ie")?"styleFloat":"cssFloat",s={cssFloat:j,styleFloat:j,"float":j};e.get=function(a,c){var b=h.byId(a),d=arguments.length;if(d==2&&c=="opacity")return f(b);var c=s[c]||c,k=e.getComputedStyle(b);return d==1?k:l(b,c,k[c]||b.style[c])};e.set=function(a,c,b){var d=h.byId(a),f=arguments.length,j=c=="opacity",c=s[c]||c;if(f==3)return j?k(d,b):d.style[c]=b;for(var m in c)e.set(a,m,c[m]);return e.getComputedStyle(d)};return e})},"dojo/mouse":function(){define(["./_base/kernel",
"./on","./has","./dom","./_base/window"],function(a,h,l,n,e){function d(a,f){var e=function(b,d){return h(b,a,function(a){if(!n.isDescendant(a.relatedTarget,f?a.target:b))return d.call(this,a)})};if(!f)e.bubble=d(a,!0);return e}l.add("dom-quirks",e.doc&&e.doc.compatMode=="BackCompat");l.add("events-mouseenter",e.doc&&"onmouseenter"in e.doc.createElement("div"));l=l("dom-quirks")&&l("ie")||!l("dom-addeventlistener")?{LEFT:1,MIDDLE:4,RIGHT:2,isButton:function(a,d){return a.button&d},isLeft:function(a){return a.button&
1},isMiddle:function(a){return a.button&4},isRight:function(a){return a.button&2}}:{LEFT:0,MIDDLE:1,RIGHT:2,isButton:function(a,d){return a.button==d},isLeft:function(a){return a.button==0},isMiddle:function(a){return a.button==1},isRight:function(a){return a.button==2}};a.mouseButtons=l;return{enter:d("mouseover"),leave:d("mouseout"),isLeft:l.isLeft,isMiddle:l.isMiddle,isRight:l.isRight}})},"dojo/keys":function(){define(["./_base/kernel","./_base/sniff"],function(a,h){return a.keys={BACKSPACE:8,
TAB:9,CLEAR:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,META:h("safari")?91:224,PAUSE:19,CAPS_LOCK:20,ESCAPE:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT_ARROW:37,UP_ARROW:38,RIGHT_ARROW:39,DOWN_ARROW:40,INSERT:45,DELETE:46,HELP:47,LEFT_WINDOW:91,RIGHT_WINDOW:92,SELECT:93,NUMPAD_0:96,NUMPAD_1:97,NUMPAD_2:98,NUMPAD_3:99,NUMPAD_4:100,NUMPAD_5:101,NUMPAD_6:102,NUMPAD_7:103,NUMPAD_8:104,NUMPAD_9:105,NUMPAD_MULTIPLY:106,NUMPAD_PLUS:107,NUMPAD_ENTER:108,NUMPAD_MINUS:109,NUMPAD_PERIOD:110,NUMPAD_DIVIDE:111,
F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,F13:124,F14:125,F15:126,NUM_LOCK:144,SCROLL_LOCK:145,UP_DPAD:175,DOWN_DPAD:176,LEFT_DPAD:177,RIGHT_DPAD:178,copyKey:h("mac")&&!h("air")?h("safari")?91:224:17}})},"dojo/_base/Deferred":function(){define(["./kernel","./lang"],function(a,h){var l=function(){},n=Object.freeze||function(){};a.Deferred=function(e){function d(a){if(k)throw Error("This deferred has already been resolved");f=a;k=!0;m()}function m(){for(var a;!a&&
j;){var d=j;j=j.next;if(a=d.progress==l)k=!1;var e=b?d.error:d.resolved;if(e)try{var o=e(f);o&&typeof o.then==="function"?o.then(h.hitch(d.deferred,"resolve"),h.hitch(d.deferred,"reject"),h.hitch(d.deferred,"progress")):(e=a&&o===void 0,a&&!e&&(b=o instanceof Error),d.deferred[e&&b?"reject":"resolve"](e?f:o))}catch(m){d.deferred.reject(m)}else b?d.deferred.reject(f):d.deferred.resolve(f)}}var f,k,b,o,j,s=this.promise={};this.resolve=this.callback=function(a){this.fired=0;this.results=[a,null];d(a)};
this.reject=this.errback=function(c){b=!0;this.fired=1;d(c);this.results=[null,c];if(!c||c.log!==!1)(a.config.deferredOnError||function(a){console.error(a)})(c)};this.progress=function(a){for(var b=j;b;){var d=b.progress;d&&d(a);b=b.next}};this.addCallbacks=function(a,b){this.then(a,b,l);return this};s.then=this.then=function(b,d,f){var e=f==l?this:new a.Deferred(s.cancel),b={resolved:b,error:d,progress:f,deferred:e};j?o=o.next=b:j=o=b;k&&m();return e.promise};var p=this;s.cancel=this.cancel=function(){if(!k){var a=
e&&e(p);if(!k)a instanceof Error||(a=Error(a)),a.log=!1,p.reject(a)}};n(s)};h.extend(a.Deferred,{addCallback:function(){return this.addCallbacks(h.hitch.apply(a,arguments))},addErrback:function(){return this.addCallbacks(null,h.hitch.apply(a,arguments))},addBoth:function(){var e=h.hitch.apply(a,arguments);return this.addCallbacks(e,e)},fired:-1});a.Deferred.when=a.when=function(a,d,h,f){if(a&&typeof a.then==="function")return a.then(d,h,f);return d?d(a):a};return a.Deferred})},"dojo/_base/json":function(){define(["./kernel",
"../json"],function(a,h){a.fromJson=function(a){return eval("("+a+")")};a._escapeString=h.stringify;a.toJsonIndentStr="\t";a.toJson=function(l,n){return h.stringify(l,function(a,d){if(d){var h=d.__json__||d.json;if(typeof h=="function")return h.call(d)}return d},n&&a.toJsonIndentStr)};return a})},"dojo/json":function(){define(["./has"],function(a){var h=typeof JSON!="undefined";a.add("json-parse",h);a.add("json-stringify",h&&JSON.stringify({a:0},function(a,e){return e||1})=='{"a":1}');if(a("json-stringify"))return JSON;
else{var l=function(a){return('"'+a.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")};return{parse:a("json-parse")?JSON.parse:function(a,e){if(e&&!/^([\s\[\{]*(?:"(?:\\.|[^"])+"|-?\d[\d\.]*(?:[Ee][+-]?\d+)?|null|true|false|)[\s\]\}]*(?:,|:|$))+$/.test(a))throw new SyntaxError("Invalid characters in JSON");return eval("("+a+")")},stringify:function(a,e,d){function h(a,b,o){e&&(a=e(o,a));var j;j=typeof a;
if(j=="number")return isFinite(a)?a+"":"null";if(j=="boolean")return a+"";if(a===null)return"null";if(typeof a=="string")return l(a);if(j=="function"||j=="undefined")return f;if(typeof a.toJSON=="function")return h(a.toJSON(o),b,o);if(a instanceof Date)return'"{FullYear}-{Month+}-{Date}T{Hours}:{Minutes}:{Seconds}Z"'.replace(/\{(\w+)(\+)?\}/g,function(b,c,d){b=a["getUTC"+c]()+(d?1:0);return b<10?"0"+b:b});if(a.valueOf()!==a)return h(a.valueOf(),b,o);var n=d?b+d:"",p=d?" ":"",c=d?"\n":"";if(a instanceof
Array){for(var p=a.length,g=[],o=0;o<p;o++)j=h(a[o],n,o),typeof j!="string"&&(j="null"),g.push(c+n+j);return"["+g.join(",")+c+b+"]"}g=[];for(o in a){var i;if(typeof o=="number")i='"'+o+'"';else if(typeof o=="string")i=l(o);else continue;j=h(a[o],n,o);typeof j=="string"&&g.push(c+n+i+":"+p+j)}return"{"+g.join(",")+c+b+"}"}var f;typeof e=="string"&&(d=e,e=null);return h(a,"","")}}}})},"dojo/_base/Color":function(){define(["./kernel","./lang","./array","./config"],function(a,h,l,n){var e=a.Color=function(a){a&&
this.setColor(a)};e.named={black:[0,0,0],silver:[192,192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255],transparent:n.transparentColor||[0,0,0,0]};h.extend(e,{r:255,g:255,b:255,a:1,_set:function(a,e,f,k){this.r=a;this.g=e;this.b=f;this.a=k},setColor:function(a){h.isString(a)?e.fromString(a,this):h.isArray(a)?
e.fromArray(a,this):(this._set(a.r,a.g,a.b,a.a),a instanceof e||this.sanitize());return this},sanitize:function(){return this},toRgb:function(){return[this.r,this.g,this.b]},toRgba:function(){return[this.r,this.g,this.b,this.a]},toHex:function(){return"#"+l.map(["r","g","b"],function(a){a=this[a].toString(16);return a.length<2?"0"+a:a},this).join("")},toCss:function(a){var e=this.r+", "+this.g+", "+this.b;return(a?"rgba("+e+", "+this.a:"rgb("+e)+")"},toString:function(){return this.toCss(!0)}});e.blendColors=
a.blendColors=function(a,h,f,k){var b=k||new e;l.forEach(["r","g","b","a"],function(e){b[e]=a[e]+(h[e]-a[e])*f;e!="a"&&(b[e]=Math.round(b[e]))});return b.sanitize()};e.fromRgb=a.colorFromRgb=function(a,h){var f=a.toLowerCase().match(/^rgba?\(([\s\.,0-9]+)\)/);return f&&e.fromArray(f[1].split(/\s*,\s*/),h)};e.fromHex=a.colorFromHex=function(a,h){var f=h||new e,k=a.length==4?4:8,b=(1<<k)-1,a=Number("0x"+a.substr(1));if(isNaN(a))return null;l.forEach(["b","g","r"],function(e){var h=a&b;a>>=k;f[e]=k==
4?17*h:h});f.a=1;return f};e.fromArray=a.colorFromArray=function(a,h){var f=h||new e;f._set(Number(a[0]),Number(a[1]),Number(a[2]),Number(a[3]));if(isNaN(f.a))f.a=1;return f.sanitize()};e.fromString=a.colorFromString=function(a,h){var f=e.named[a];return f&&e.fromArray(f,h)||e.fromRgb(a,h)||e.fromHex(a,h)};return e})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define(["../ready","./kernel","./connect","./unload","./window","./event","./html","./NodeList",
"../query","./xhr","./fx"],function(a){return a})},"dojo/_base/unload":function(){define(["./kernel","./connect"],function(a,h){var l=window;a.addOnWindowUnload=function(n,e){if(!a.windowUnloaded)h.connect(l,"unload",a.windowUnloaded=function(){});h.connect(l,"unload",n,e)};a.addOnUnload=function(a,e){h.connect(l,"beforeunload",a,e)};return{addOnWindowUnload:a.addOnWindowUnload,addOnUnload:a.addOnUnload}})},"dojo/_base/html":function(){define(["./kernel","../dom","../dom-style","../dom-attr","../dom-prop",
"../dom-class","../dom-construct","../dom-geometry"],function(a,h,l,n,e,d,m,f){a.byId=h.byId;a.isDescendant=h.isDescendant;a.setSelectable=h.setSelectable;a.getAttr=n.get;a.setAttr=n.set;a.hasAttr=n.has;a.removeAttr=n.remove;a.getNodeProp=n.getNodeProp;a.attr=function(a,b,d){if(arguments.length==2)return n[typeof b=="string"?"get":"set"](a,b);return n.set(a,b,d)};a.hasClass=d.contains;a.addClass=d.add;a.removeClass=d.remove;a.toggleClass=d.toggle;a.replaceClass=d.replace;a._toDom=a.toDom=m.toDom;
a.place=m.place;a.create=m.create;a.empty=function(a){m.empty(a)};a._destroyElement=a.destroy=function(a){m.destroy(a)};a._getPadExtents=a.getPadExtents=f.getPadExtents;a._getBorderExtents=a.getBorderExtents=f.getBorderExtents;a._getPadBorderExtents=a.getPadBorderExtents=f.getPadBorderExtents;a._getMarginExtents=a.getMarginExtents=f.getMarginExtents;a._getMarginSize=a.getMarginSize=f.getMarginSize;a._getMarginBox=a.getMarginBox=f.getMarginBox;a.setMarginBox=f.setMarginBox;a._getContentBox=a.getContentBox=
f.getContentBox;a.setContentSize=f.setContentSize;a._isBodyLtr=a.isBodyLtr=f.isBodyLtr;a._docScroll=a.docScroll=f.docScroll;a._getIeDocumentElementOffset=a.getIeDocumentElementOffset=f.getIeDocumentElementOffset;a._fixIeBiDiScrollLeft=a.fixIeBiDiScrollLeft=f.fixIeBiDiScrollLeft;a.position=f.position;a.marginBox=function(a,b){return b?f.setMarginBox(a,b):f.getMarginBox(a)};a.contentBox=function(a,b){return b?f.setContentSize(a,b):f.getContentBox(a)};a.coords=function(d,b){a.deprecated("dojo.coords()",
"Use dojo.position() or dojo.marginBox().");var d=h.byId(d),e=l.getComputedStyle(d),e=f.getMarginBox(d,e),j=f.position(d,b);e.x=j.x;e.y=j.y;return e};a.getProp=e.get;a.setProp=e.set;a.prop=function(a,b,d){if(arguments.length==2)return e[typeof b=="string"?"get":"set"](a,b);return e.set(a,b,d)};a.getStyle=l.get;a.setStyle=l.set;a.getComputedStyle=l.getComputedStyle;a.__toPixelValue=a.toPixelValue=l.toPixelValue;a.style=function(a,b,d){switch(arguments.length){case 1:return l.get(a);case 2:return l[typeof b==
"string"?"get":"set"](a,b)}return l.set(a,b,d)};return a})},"dojo/dom-attr":function(){define(["exports","./_base/sniff","./_base/lang","./dom","./dom-style","./dom-prop"],function(a,h,l,n,e,d){function m(a,d){var e=a.getAttributeNode&&a.getAttributeNode(d);return e&&e.specified}var f={innerHTML:1,className:1,htmlFor:h("ie"),value:1},k={classname:"class",htmlfor:"for",tabindex:"tabIndex",readonly:"readOnly"};a.has=function(a,e){var h=e.toLowerCase();return f[d.names[h]||e]||m(n.byId(a),k[h]||e)};
a.get=function(a,e){var a=n.byId(a),h=e.toLowerCase(),s=d.names[h]||e,p=f[s];value=a[s];if(p&&typeof value!="undefined")return value;if(s!="href"&&(typeof value=="boolean"||l.isFunction(value)))return value;h=k[h]||e;return m(a,h)?a.getAttribute(h):null};a.set=function(b,h,j){b=n.byId(b);if(arguments.length==2){for(var m in h)a.set(b,m,h[m]);return b}m=h.toLowerCase();var p=d.names[m]||h,c=f[p];if(p=="style"&&typeof j!="string")return e.set(b,j),b;if(c||typeof j=="boolean"||l.isFunction(j))return d.set(b,
h,j);b.setAttribute(k[m]||h,j);return b};a.remove=function(a,d){n.byId(a).removeAttribute(k[d.toLowerCase()]||d)};a.getNodeProp=function(a,e){var a=n.byId(a),f=e.toLowerCase(),h=d.names[f]||e;if(h in a&&h!="href")return a[h];f=k[f]||e;return m(a,f)?a.getAttribute(f):null}})},"dojo/dom-prop":function(){define(["exports","./_base/kernel","./_base/sniff","./_base/lang","./dom","./dom-style","./dom-construct","./_base/connect"],function(a,h,l,n,e,d,m,f){var k={},b=0,o=h._scopeName+"attrid",j={col:1,colgroup:1,
table:1,tbody:1,tfoot:1,thead:1,tr:1,title:1};a.names={"class":"className","for":"htmlFor",tabindex:"tabIndex",readonly:"readOnly",colspan:"colSpan",frameborder:"frameBorder",rowspan:"rowSpan",valuetype:"valueType"};a.get=function(b,d){var b=e.byId(b),c=d.toLowerCase();return b[a.names[c]||d]};a.set=function(h,p,c){h=e.byId(h);if(arguments.length==2&&typeof p!="string"){for(var g in p)a.set(h,g,p[g]);return h}g=p.toLowerCase();g=a.names[g]||p;if(g=="style"&&typeof c!="string")return d.style(h,c),
h;if(g=="innerHTML")return l("ie")&&h.tagName.toLowerCase()in j?(m.empty(h),h.appendChild(m.toDom(c,h.ownerDocument))):h[g]=c,h;if(n.isFunction(c)){var i=h[o];i||(i=b++,h[o]=i);k[i]||(k[i]={});var q=k[i][g];if(q)f.disconnect(q);else try{delete h[g]}catch(u){}c?k[i][g]=f.connect(h,g,c):h[g]=null;return h}h[g]=c;return h}})},"dojo/dom-construct":function(){define(["exports","./_base/kernel","./_base/sniff","./_base/window","./dom","./dom-attr","./on"],function(a,h,l,n,e,d,m){function f(a,b){var c=b.parentNode;
c&&c.insertBefore(a,b)}var k={option:["select"],tbody:["table"],thead:["table"],tfoot:["table"],tr:["table","tbody"],td:["table","tbody","tr"],th:["table","thead","tr"],legend:["fieldset"],caption:["table"],colgroup:["table"],col:["table","colgroup"],li:["ul"]},b=/<\s*([\w\:]+)/,o={},j=0,s="__"+h._scopeName+"ToDomId",p;for(p in k)if(k.hasOwnProperty(p))h=k[p],h.pre=p=="option"?'<select multiple="multiple">':"<"+h.join("><")+">",h.post="</"+h.reverse().join("></")+">";var c=null,g;m(window,"unload",
function(){c=null});a.toDom=function(a,c){var c=c||n.doc,d=c[s];d||(c[s]=d=++j+"",o[d]=c.createElement("div"));a+="";var e=a.match(b),f=e?e[1].toLowerCase():"",d=o[d];if(e&&k[f]){e=k[f];d.innerHTML=e.pre+a+e.post;for(e=e.length;e;--e)d=d.firstChild}else d.innerHTML=a;if(d.childNodes.length==1)return d.removeChild(d.firstChild);for(f=c.createDocumentFragment();e=d.firstChild;)f.appendChild(e);return f};a.place=function(b,c,d){c=e.byId(c);typeof b=="string"&&(b=/^\s*</.test(b)?a.toDom(b,c.ownerDocument):
e.byId(b));if(typeof d=="number"){var g=c.childNodes;!g.length||g.length<=d?c.appendChild(b):f(b,g[d<0?0:d])}else switch(d){case "before":f(b,c);break;case "after":d=b;(g=c.parentNode)&&(g.lastChild==c?g.appendChild(d):g.insertBefore(d,c.nextSibling));break;case "replace":c.parentNode.replaceChild(b,c);break;case "only":a.empty(c);c.appendChild(b);break;case "first":if(c.firstChild){f(b,c.firstChild);break}default:c.appendChild(b)}return b};a.create=function(b,c,f,g){var h=n.doc;if(f)f=e.byId(f),
h=f.ownerDocument;typeof b=="string"&&(b=h.createElement(b));c&&d.set(b,c);f&&a.place(b,f,g);return b};a.empty=l("ie")?function(b){for(var b=e.byId(b),c;c=b.lastChild;)a.destroy(c)}:function(a){e.byId(a).innerHTML=""};a.destroy=function(a){a=e.byId(a);try{var b=a.ownerDocument;if(!c||g!=b)c=b.createElement("div"),g=b;c.appendChild(a.parentNode?a.parentNode.removeChild(a):a);c.innerHTML=""}catch(d){}}})},"dojo/dom-class":function(){define(["./_base/lang","./_base/array","./dom"],function(a,h,l){function n(a){if(typeof a==
"string"||a instanceof String){if(a&&!d.test(a))return m[0]=a,m;a=a.split(d);a.length&&!a[0]&&a.shift();a.length&&!a[a.length-1]&&a.pop();return a}if(!a)return[];return h.filter(a,function(a){return a})}var e,d=/\s+/,m=[""],f={};return e={contains:function(a,b){return(" "+l.byId(a).className+" ").indexOf(" "+b+" ")>=0},add:function(a,b){var a=l.byId(a),b=n(b),d=a.className,e,d=d?" "+d+" ":" ";e=d.length;for(var f=0,h=b.length,c;f<h;++f)(c=b[f])&&d.indexOf(" "+c+" ")<0&&(d+=c+" ");e<d.length&&(a.className=
d.substr(1,d.length-2))},remove:function(d,b){var d=l.byId(d),e;if(b!==void 0){b=n(b);e=" "+d.className+" ";for(var f=0,h=b.length;f<h;++f)e=e.replace(" "+b[f]+" "," ");e=a.trim(e)}else e="";d.className!=e&&(d.className=e)},replace:function(a,b,d){a=l.byId(a);f.className=a.className;e.remove(f,d);e.add(f,b);a.className!==f.className&&(a.className=f.className)},toggle:function(a,b,d){a=l.byId(a);if(d===void 0)for(var b=n(b),f=0,h=b.length,m;f<h;++f)m=b[f],e[e.contains(a,m)?"remove":"add"](a,m);else e[d?
"add":"remove"](a,b);return d}}})},"dojo/_base/NodeList":function(){define(["./kernel","../query","./array","./html","../NodeList-dom"],function(a,h,l){var h=h.NodeList,n=h.prototype;n.connect=h._adaptAsForEach(function(){return a.connect.apply(this,arguments)});n.coords=h._adaptAsMap(a.coords);h.events=["blur","focus","change","click","error","keydown","keypress","keyup","load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","submit"];l.forEach(h.events,function(a){var d=
"on"+a;n[d]=function(a,e){return this.connect(d,a,e)}});a.NodeList=h;return a.NodeList})},"dojo/query":function(){define(["./_base/kernel","./has","./dom","./on","./_base/array","./_base/lang","./selector/_loader","./selector/_loader!default"],function(a,h,l,n,e,d,m,f){function k(a,b){var c=function(c,d){if(typeof d=="string"&&(d=l.byId(d),!d))return new b([]);var e=typeof c=="string"?a(c,d):c.orphan?c:[c];if(e.orphan)return e;return new b(e)};c.matches=a.match||function(a,b,d){return c.filter([a],
b,d).length>0};c.filter=a.filter||function(a,b,d){return c(b,d).filter(function(b){return e.indexOf(a,b)>-1})};if(typeof a!="function")var d=a.search,a=function(a,b){return d(b||document,a)};return c}h.add("array-extensible",function(){return d.delegate([],{length:1}).length==1&&!h("bug-for-in-skips-shadowed")});var b=Array.prototype,o=b.slice,j=b.concat,s=e.forEach,p=function(b,c,d){c=[0].concat(o.call(c,0));d=d||a.global;return function(a){c[0]=a;return b.apply(d,c)}},c=function(a){var b=this instanceof
g&&h("array-extensible");typeof a=="number"&&(a=Array(a));var c=a&&"length"in a?a:arguments;if(b||!c.sort){for(var e=b?this:[],f=e.length=c.length,j=0;j<f;j++)e[j]=c[j];if(b)return e;c=e}d._mixin(c,i);c._NodeListCtor=function(a){return g(a)};return c},g=c,i=g.prototype=h("array-extensible")?[]:{};g._wrap=i._wrap=function(a,b,c){a=new (c||this._NodeListCtor||g)(a);return b?a._stash(b):a};g._adaptAsMap=function(a,b){return function(){return this.map(p(a,arguments,b))}};g._adaptAsForEach=function(a,
b){return function(){this.forEach(p(a,arguments,b));return this}};g._adaptAsFilter=function(a,b){return function(){return this.filter(p(a,arguments,b))}};g._adaptWithCondition=function(b,c,d){return function(){var e=arguments,f=p(b,e,d);if(c.call(d||a.global,e))return this.map(f);this.forEach(f);return this}};s(["slice","splice"],function(a){var c=b[a];i[a]=function(){return this._wrap(c.apply(this,arguments),a=="slice"?this:null)}});s(["indexOf","lastIndexOf","every","some"],function(b){var c=e[b];
i[b]=function(){return c.apply(a,[this].concat(o.call(arguments,0)))}});d.extend(c,{constructor:g,_NodeListCtor:g,toString:function(){return this.join(",")},_stash:function(a){this._parent=a;return this},on:function(a,b){var c=this.map(function(c){return n(c,a,b)});c.remove=function(){for(var a=0;a<c.length;a++)c[a].remove()};return c},end:function(){return this._parent?this._parent:new this._NodeListCtor(0)},concat:function(){var a=d.isArray(this)?this:o.call(this,0),b=e.map(arguments,function(a){return a&&
!d.isArray(a)&&(typeof c!="undefined"&&a.constructor===c||a.constructor===this._NodeListCtor)?o.call(a,0):a});return this._wrap(j.apply(a,b),this)},map:function(a,b){return this._wrap(e.map(this,a,b),this)},forEach:function(a,b){s(this,a,b);return this},filter:function(a){var b=arguments,c=this,d=0;if(typeof a=="string"){c=q._filterResult(this,b[0]);if(b.length==1)return c._stash(this);d=1}return this._wrap(e.filter(c,b[d],b[d+1]),this)},instantiate:function(a,b){var c=d.isFunction(a)?a:d.getObject(a),
b=b||{};return this.forEach(function(a){new c(b,a)})},at:function(){var a=new this._NodeListCtor(0);s(arguments,function(b){b<0&&(b=this.length+b);this[b]&&a.push(this[b])},this);return a._stash(this)}});var q=k(f,c);a.query=k(f,function(a){return c(a)});q.load=function(a,b,d){m.load(a,b,function(a){d(k(a,c))})};a._filterQueryResult=q._filterResult=function(a,b,d){return new c(q.filter(a,b,d))};a.NodeList=q.NodeList=c;return q})},"dojo/selector/_loader":function(){define(["../has","require"],function(a,
h){var l=document.createElement("div");a.add("dom-qsa2.1",!!l.querySelectorAll);a.add("dom-qsa3",function(){try{return l.innerHTML="<p class='TEST'></p>",l.querySelectorAll(".TEST:empty").length==1}catch(a){}});var n;return{load:function(e,d,m){var f=h,e=e=="default"?a("config-selectorEngine")||"css3":e,e=e=="css2"||e=="lite"?"./lite":e=="css2.1"?a("dom-qsa2.1")?"./lite":"./acme":e=="css3"?a("dom-qsa3")?"./lite":"./acme":e=="acme"?"./acme":(f=d)&&e;if(e.charAt(e.length-1)=="?")var e=e.substring(0,
e.length-1),k=!0;if(k&&(a("dom-compliant-qsa")||n))return m(n);f([e],function(a){e!="./lite"&&(n=a);m(a)})}}})},"dojo/selector/acme":function(){define(["../_base/kernel","../has","../dom","../_base/sniff","../_base/array","../_base/lang","../_base/window"],function(a,h,l){var n=a.trim,e=a.forEach,d=(a.isWebKit||a.isMozilla)&&a.doc.compatMode=="BackCompat",m=!1,f=function(){return!0},k=function(a){a+=">~+".indexOf(a.slice(-1))>=0?" * ":" ";for(var b=function(b,c){return n(a.slice(b,c))},c=[],d=-1,
e=-1,f=-1,g=-1,h=-1,i=-1,j=-1,k="",l="",o,x=0,p=a.length,q=null,r=null,u=function(){if(i>=0)q.id=b(i,x).replace(/\\/g,""),i=-1;if(j>=0){var a=j==x?null:b(j,x);q[">~+".indexOf(a)<0?"tag":"oper"]=a;j=-1}h>=0&&(q.classes.push(b(h+1,x).replace(/\\/g,"")),h=-1)};k=l,l=a.charAt(x),x<p;x++)if(k!="\\")if(q||(o=x,q={query:null,pseudos:[],attrs:[],classes:[],tag:null,oper:null,id:null,getTag:function(){return m?this.otag:this.tag}},j=x),d>=0)if(l=="]"){r.attr?r.matchFor=b(f||d+1,x):r.attr=b(d+1,x);if((d=r.matchFor)&&
(d.charAt(0)=='"'||d.charAt(0)=="'"))r.matchFor=d.slice(1,-1);q.attrs.push(r);r=null;d=f=-1}else{if(l=="=")f="|~^$*".indexOf(k)>=0?k:"",r.type=f+l,r.attr=b(d+1,x-f.length),f=x+1}else if(e>=0){if(l==")"){if(g>=0)r.value=b(e+1,x);g=e=-1}}else if(l=="#")u(),i=x+1;else if(l==".")u(),h=x;else if(l==":")u(),g=x;else if(l=="[")u(),d=x,r={};else if(l=="(")g>=0&&(r={name:b(g+1,x),value:null},q.pseudos.push(r)),e=x;else if(l==" "&&k!=l){u();g>=0&&q.pseudos.push({name:b(g+1,x)});q.loops=q.pseudos.length||q.attrs.length||
q.classes.length;q.oquery=q.query=b(o,x);q.otag=q.tag=q.oper?null:q.tag||"*";if(q.tag)q.tag=q.tag.toUpperCase();if(c.length&&c[c.length-1].oper)q.infixOper=c.pop(),q.query=q.infixOper.query+" "+q.query;c.push(q);q=null}return c},b=function(a,b){if(!a)return b;if(!b)return a;return function(){return a.apply(window,arguments)&&b.apply(window,arguments)}},o=function(a,b){var c=b||[];a&&c.push(a);return c},j=function(a){return 1==a.nodeType},s=function(a,b){if(!a)return"";if(b=="class")return a.className||
"";if(b=="for")return a.htmlFor||"";if(b=="style")return a.style.cssText||"";return(m?a.getAttribute(b):a.getAttribute(b,2))||""},p={"*=":function(a,b){return function(c){return s(c,a).indexOf(b)>=0}},"^=":function(a,b){return function(c){return s(c,a).indexOf(b)==0}},"$=":function(a,b){return function(c){c=" "+s(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return(" "+s(b,a)+" ").indexOf(c)>=0}},"|=":function(a,b){var c=b+"-";return function(d){d=
s(d,a);return d==b||d.indexOf(c)==0}},"=":function(a,b){return function(c){return s(c,a)==b}}},c=typeof a.doc.firstChild.nextElementSibling=="undefined",g=!c?"nextElementSibling":"nextSibling",i=!c?"previousElementSibling":"previousSibling",q=c?j:f,u=function(a){for(;a=a[i];)if(q(a))return!1;return!0},r=function(a){for(;a=a[g];)if(q(a))return!1;return!0},t=function(a){var b=a.parentNode,c=0,d=b.children||b.childNodes,e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&e>=0&&f>=0)return e;b._l=
d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[g])if(q(b))b._i=++c,a===b&&(e=c);return e},A=function(a){return!(t(a)%2)},w=function(a){return t(a)%2},I={checked:function(){return function(a){return!!("checked"in a?a.checked:a.selected)}},"first-child":function(){return u},"last-child":function(){return r},"only-child":function(){return function(a){return u(a)&&r(a)}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;a>=0;a--){var c=b[a].nodeType;if(c===1||c==
3)return!1}return!0}},contains:function(a,b){var c=b.charAt(0);if(c=='"'||c=="'")b=b.slice(1,-1);return function(a){return a.innerHTML.indexOf(b)>=0}},not:function(a,b){var c=k(b)[0],d={el:1};if(c.tag!="*")d.tag=1;if(!c.classes.length)d.classes=1;var e=D(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){var c=parseInt;if(b=="odd")return w;else if(b=="even")return A;if(b.indexOf("n")!=-1){var d=b.split("n",2),e=d[0]?d[0]=="-"?-1:c(d[0]):1,f=d[1]?c(d[1]):0,g=0,h=-1;e>0?f<0?f=f%e&&e+f%
e:f>0&&(f>=e&&(g=f-f%e),f%=e):e<0&&(e*=-1,f>0&&(h=f,f%=e));if(e>0)return function(a){a=t(a);return a>=g&&(h<0||a<=h)&&a%e==f};else b=f}var i=c(b);return function(a){return t(a)==i}}},R=a.isIE&&(a.isIE<9||a.isQuirks)?function(a){var b=a.toLowerCase();b=="class"&&(a="className");return function(c){return m?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},D=function(a,c){if(!a)return f;var c=c||{},d=null;"el"in c||(d=b(d,j));"tag"in c||a.tag!=
"*"&&(d=b(d,function(b){return b&&b.tagName==a.getTag()}));"classes"in c||e(a.classes,function(a,c){var e=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");d=b(d,function(a){return e.test(a.className)});d.count=c});"pseudos"in c||e(a.pseudos,function(a){var c=a.name;I[c]&&(d=b(d,I[c](c,a.value)))});"attrs"in c||e(a.attrs,function(a){var c,e=a.attr;a.type&&p[a.type]?c=p[a.type](e,a.matchFor):e.length&&(c=R(e));c&&(d=b(d,c))});"id"in c||a.id&&(d=b(d,function(b){return!!b&&b.id==a.id}));d||"default"in c||(d=f);return d},
S=function(a){return function(b,d,e){for(;b=b[g];)if(!c||j(b)){(!e||y(b,e))&&a(b)&&d.push(b);break}return d}},x=function(a){return function(b,c,d){for(b=b[g];b;){if(q(b)){if(d&&!y(b,d))break;a(b)&&c.push(b)}b=b[g]}return c}},P=function(a){a=a||f;return function(b,c,d){for(var e=0,f=b.children||b.childNodes;b=f[e++];)q(b)&&(!d||y(b,d))&&a(b,e)&&c.push(b);return c}},v={},B=function(b){var c=v[b.query];if(c)return c;var e=b.infixOper,e=e?e.oper:"",g=D(b,{el:1}),h="*"==b.tag,i=a.doc.getElementsByClassName;
if(e){i={el:1};if(h)i.tag=1;g=D(b,i);"+"==e?c=S(g):"~"==e?c=x(g):">"==e&&(c=P(g))}else if(b.id)g=!b.loops&&h?f:D(b,{el:1,id:1}),c=function(a,c){var d=l.byId(b.id,a.ownerDocument||a);if(d&&g(d))if(9==a.nodeType)return o(d,c);else{for(var e=d.parentNode;e;){if(e==a)break;e=e.parentNode}if(e)return o(d,c)}};else if(i&&/\{\s*\[native code\]\s*\}/.test(String(i))&&b.classes.length&&!d)var g=D(b,{el:1,classes:1,id:1}),j=b.classes.join(" "),c=function(a,b,c){for(var b=o(0,b),d,e=0,f=a.getElementsByClassName(j);d=
f[e++];)g(d,a)&&y(d,c)&&b.push(d);return b};else!h&&!b.loops?c=function(a,c,d){for(var c=o(0,c),e=0,f=a.getElementsByTagName(b.getTag());a=f[e++];)y(a,d)&&c.push(a);return c}:(g=D(b,{el:1,tag:1,id:1}),c=function(a,c,d){for(var c=o(0,c),e,f=0,h=a.getElementsByTagName(b.getTag());e=h[f++];)g(e,a)&&y(e,d)&&c.push(e);return c});return v[b.query]=c},F={},C={},E=function(a){var b=k(n(a));if(b.length==1){var c=B(b[0]);return function(a){if(a=c(a,[]))a.nozip=!0;return a}}return function(a){for(var a=o(a),
c,d,e=b.length,f,g,h=0;h<e;h++){g=[];c=b[h];d=a.length-1;if(d>0)f={},g.nozip=!0;d=B(c);for(var i=0;c=a[i];i++)d(c,g,f);if(!g.length)break;a=g}return g}},h=navigator.userAgent,h=a.isWebKit&&h.indexOf("WebKit/")>0&&parseFloat(h.split("WebKit/")[1])>528,G=a.isIE?"commentStrip":"nozip",K=!!a.doc.querySelectorAll&&(!a.isSafari||a.isSafari>3.1||h),V=/n\+\d|([^ ])?([>~+])([^ =])?/g,W=function(a,b,c,d){return c?(b?b+" ":"")+c+(d?" "+d:""):a},L=function(b,c){b=b.replace(V,W);if(K){var e=C[b];if(e&&!c)return e}if(e=
F[b])return e;var e=b.charAt(0),f=-1==b.indexOf(" ");b.indexOf("#")>=0&&f&&(c=!0);if(K&&!c&&">~+".indexOf(e)==-1&&(!a.isIE||b.indexOf(":")==-1)&&!(d&&b.indexOf(".")>=0)&&b.indexOf(":contains")==-1&&b.indexOf(":checked")==-1&&b.indexOf("|=")==-1){var g=">~+".indexOf(b.charAt(b.length-1))>=0?b+" *":b;return C[b]=function(a){try{if(!(9==a.nodeType||f))throw"";var c=a.querySelectorAll(g);c[G]=!0;return c}catch(d){return L(b,!0)(a)}}}else{var h=b.split(/\s*,\s*/);return F[b]=h.length<2?E(b):function(a){for(var b=
0,c=[],d;d=h[b++];)c=c.concat(E(d)(a));return c}}},z=0,M=a.isIE?function(a){return m?a.getAttribute("_uid")||a.setAttribute("_uid",++z)||z:a.uniqueID}:function(a){return a._uid||(a._uid=++z)},y=function(a,b){if(!b)return 1;var c=M(a);if(!b[c])return b[c]=1;return 0},H=function(b){if(b&&b.nozip)return b;var c=[];if(!b||!b.length)return c;b[0]&&c.push(b[0]);if(b.length<2)return c;z++;if(a.isIE&&m){var d=z+"";b[0].setAttribute("_zipIdx",d);for(var e=1,f;f=b[e];e++)b[e].getAttribute("_zipIdx")!=d&&c.push(f),
f.setAttribute("_zipIdx",d)}else if(a.isIE&&b.commentStrip)try{for(e=1;f=b[e];e++)j(f)&&c.push(f)}catch(g){}else{b[0]&&(b[0]._zipIdx=z);for(e=1;f=b[e];e++)b[e]._zipIdx!=z&&c.push(f),f._zipIdx=z}return c},h=function(b,c){var c=c||a.doc,d=c.ownerDocument||c.documentElement;m=c.contentType&&c.contentType=="application/xml"||a.isOpera&&(c.doctype||d.toString()=="[object XMLDocument]")||!!d&&(a.isIE?d.xml:c.xmlVersion||d.xmlVersion);if((d=L(b)(c))&&d.nozip)return d;return H(d)};h.filter=function(b,c,d){for(var e=
[],f=k(c),f=f.length==1&&!/[^\w#\.]/.test(c)?D(f[0]):function(b){return a.query(c,d).indexOf(b)!=-1},g=0,h;h=b[g];g++)f(h)&&e.push(h);return e};return h})},"dojo/NodeList-dom":function(){define("dojo/NodeList-dom",["./_base/kernel","./query","./_base/array","./_base/lang","./dom-class","./dom-construct","./dom-geometry","./dom-attr","./dom-style"],function(a,h,l,n,e,d,m,f,k){function b(a){return function(b,c,d){if(arguments.length==2)return a[typeof c=="string"?"get":"set"](b,c);return a.set(b,c,
d)}}var o=function(a){return a.length==1&&typeof a[0]=="string"},j=function(a){var b=a.parentNode;b&&b.removeChild(a)},s=h.NodeList,p=s._adaptWithCondition,c=s._adaptAsForEach,g=s._adaptAsMap;n.extend(s,{_normalize:function(b,c){var e=b.parse===!0;if(typeof b.template=="string")var f=b.templateFunc||a.string&&a.string.substitute,b=f?f(b.template,b):b;f=typeof b;f=="string"||f=="number"?(b=d.toDom(b,c&&c.ownerDocument),b=b.nodeType==11?n._toArray(b.childNodes):[b]):n.isArrayLike(b)?n.isArray(b)||(b=
n._toArray(b)):b=[b];if(e)b._runParse=!0;return b},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(b,c,e,f){if(!(c.nodeType!=1&&e=="only"))for(var g,h=b.length,j=h-1;j>=0;j--){var k=f?this._cloneNode(b[j]):b[j];if(b._runParse&&a.parser&&a.parser.parse){g||(g=c.ownerDocument.createElement("div"));g.appendChild(k);a.parser.parse(g);for(k=g.firstChild;g.firstChild;)g.removeChild(g.firstChild)}j==h-1?d.place(k,c,e):c.parentNode.insertBefore(k,c);c=k}},attr:p(b(f),o),style:p(b(k),o),addClass:c(e.add),
removeClass:c(e.remove),replaceClass:c(e.replace),toggleClass:c(e.toggle),empty:c(d.empty),removeAttr:c(f.remove),position:g(m.position),marginBox:g(m.getMarginBox),place:function(a,b){var c=h(a)[0];return this.forEach(function(a){d.place(a,c,b)})},orphan:function(a){return(a?h._filterResult(this,a):this).forEach(j)},adopt:function(a,b){return h(a).place(this[0],b)._stash(this)},query:function(a){if(!a)return this;var b=new s;this.map(function(c){h(a,c).forEach(function(a){a!==void 0&&b.push(a)})});
return b._stash(this)},filter:function(a){var b=arguments,c=this,d=0;if(typeof a=="string"){c=h._filterResult(this,b[0]);if(b.length==1)return c._stash(this);d=1}return this._wrap(l.filter(c,b[d],b[d+1]),this)},addContent:function(a,b){for(var a=this._normalize(a,this[0]),c=0,d;d=this[c];c++)this._place(a,d,b,c>0);return this}});return s})},"dojo/_base/xhr":function(){define(["./kernel","./sniff","require","../io-query","../dom","../dom-form","./Deferred","./json","./lang","./array","../on"],function(a,
h,l,n,e,d,m,f,k,b,o){h.add("native-xhr",function(){return typeof XMLHttpRequest!=="undefined"});if(l.getXhr)a._xhrObj=l.getXhr;else if(h("native-xhr"))a._xhrObj=function(){try{return new XMLHttpRequest}catch(a){throw Error("XMLHTTP not available: "+a);}};else{for(var l=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],j,s=0;s<3;)try{if(j=l[s++],new ActiveXObject(j))break}catch(p){}a._xhrObj=function(){return new ActiveXObject(j)}}var c=a.config;a.objectToQuery=n.objectToQuery;a.queryToObject=
n.queryToObject;a.fieldToObject=d.fieldToObject;a.formToObject=d.toObject;a.formToQuery=d.toQuery;a.formToJson=d.toJson;a._blockAsync=!1;var g=a._contentHandlers=a.contentHandlers={text:function(a){return a.responseText},json:function(a){return f.fromJson(a.responseText||null)},"json-comment-filtered":function(b){a.config.useCommentedJson||console.warn("Consider using the standard mimetype:application/json. json-commenting can introduce security issues. To decrease the chances of hijacking, use the standard the 'json' handler and prefix your json with: {}&&\nUse djConfig.useCommentedJson=true to turn off this message.");
var b=b.responseText,c=b.indexOf("/*"),d=b.lastIndexOf("*/");if(c==-1||d==-1)throw Error("JSON was not comment filtered");return f.fromJson(b.substring(c+2,d))},javascript:function(b){return a.eval(b.responseText)},xml:function(a){var c=a.responseXML;if(h("ie")&&(!c||!c.documentElement)){var d=function(a){return"MSXML"+a+".DOMDocument"},d=["Microsoft.XMLDOM",d(6),d(4),d(3),d(2)];b.some(d,function(b){try{var d=new ActiveXObject(b);d.async=!1;d.loadXML(a.responseText);c=d}catch(e){return!1}return!0})}return c},
"json-comment-optional":function(a){return a.responseText&&/^[^{\[]*\/\*/.test(a.responseText)?g["json-comment-filtered"](a):g.json(a)}};a._ioSetArgs=function(b,f,g,h){var i={args:b,url:b.url},j=null;if(b.form){var j=e.byId(b.form),l=j.getAttributeNode("action");i.url=i.url||(l?l.value:null);j=d.toObject(j)}l=[{}];j&&l.push(j);b.content&&l.push(b.content);b.preventCache&&l.push({"dojo.preventCache":(new Date).valueOf()});i.query=n.objectToQuery(k.mixin.apply(null,l));i.handleAs=b.handleAs||"text";
var o=new m(f);o.addCallbacks(g,function(a){return h(a,o)});var p=b.load;p&&k.isFunction(p)&&o.addCallback(function(a){return p.call(b,a,i)});var q=b.error;q&&k.isFunction(q)&&o.addErrback(function(a){return q.call(b,a,i)});var r=b.handle;r&&k.isFunction(r)&&o.addBoth(function(a){return r.call(b,a,i)});c.ioPublish&&a.publish&&i.args.ioPublish!==!1&&(o.addCallbacks(function(b){a.publish("/dojo/io/load",[o,b]);return b},function(b){a.publish("/dojo/io/error",[o,b]);return b}),o.addBoth(function(b){a.publish("/dojo/io/done",
[o,b]);return b}));o.ioArgs=i;return o};var i=function(a){a.canceled=!0;var b=a.ioArgs.xhr,c=typeof b.abort;(c=="function"||c=="object"||c=="unknown")&&b.abort();a=a.ioArgs.error;if(!a)a=Error("xhr cancelled"),a.dojoType="cancel";return a},q=function(a){a=g[a.ioArgs.handleAs](a.ioArgs.xhr);return a===void 0?null:a},u=function(a,b){b.ioArgs.args.failOk||console.error(a);return a},r=null,t=[],A=0,w=function(b){A<=0&&(A=0,c.ioPublish&&a.publish&&(!b||b&&b.ioArgs.args.ioPublish!==!1)&&a.publish("/dojo/io/stop"))},
I=function(){var b=(new Date).getTime();if(!a._blockAsync)for(var c=0,d;c<t.length&&(d=t[c]);c++){var e=d.dfd,f=function(){if(!e||e.canceled||!d.validCheck(e))t.splice(c--,1),A-=1;else if(d.ioCheck(e))t.splice(c--,1),d.resHandle(e),A-=1;else if(e.startTime&&e.startTime+(e.ioArgs.args.timeout||0)<b){t.splice(c--,1);var a=Error("timeout exceeded");a.dojoType="timeout";e.errback(a);e.cancel();A-=1}};if(a.config.debugAtAllCosts)f.call(this);else try{f.call(this)}catch(g){e.errback(g)}}w(e);t.length||
(clearInterval(r),r=null)};a._ioCancelAll=function(){try{b.forEach(t,function(a){try{a.dfd.cancel()}catch(b){}})}catch(a){}};h("ie")&&o(window,"unload",a._ioCancelAll);a._ioNotifyStart=function(b){c.ioPublish&&a.publish&&b.ioArgs.args.ioPublish!==!1&&(A||a.publish("/dojo/io/start"),A+=1,a.publish("/dojo/io/send",[b]))};a._ioWatch=function(a,b,c,d){var e=a.ioArgs.args;if(e.timeout)a.startTime=(new Date).getTime();t.push({dfd:a,validCheck:b,ioCheck:c,resHandle:d});r||(r=setInterval(I,50));e.sync&&I()};
var R=function(a){return a.ioArgs.xhr.readyState},D=function(a){return 4==a.ioArgs.xhr.readyState},S=function(b){var c=b.ioArgs.xhr;if(a._isDocumentOk(c))b.callback(b);else{var d=Error("Unable to load "+b.ioArgs.url+" status:"+c.status);d.status=c.status;d.responseText=c.responseText;d.xhr=c;b.errback(d)}};a._ioAddQueryToUrl=function(a){if(a.query.length)a.url+=(a.url.indexOf("?")==-1?"?":"&")+a.query,a.query=null};a.xhr=function(b,c,d){var e=a._ioSetArgs(c,i,q,u),f=e.ioArgs,g=f.xhr=a._xhrObj(f.args);
if(!g)return e.cancel(),e;"postData"in c?f.query=c.postData:"putData"in c?f.query=c.putData:"rawBody"in c?f.query=c.rawBody:(arguments.length>2&&!d||"POST|PUT".indexOf(b.toUpperCase())==-1)&&a._ioAddQueryToUrl(f);g.open(b,f.url,c.sync!==!0,c.user||void 0,c.password||void 0);if(c.headers)for(var h in c.headers)h.toLowerCase()==="content-type"&&!c.contentType?c.contentType=c.headers[h]:c.headers[h]&&g.setRequestHeader(h,c.headers[h]);c.contentType!==!1&&g.setRequestHeader("Content-Type",c.contentType||
"application/x-www-form-urlencoded");(!c.headers||!("X-Requested-With"in c.headers))&&g.setRequestHeader("X-Requested-With","XMLHttpRequest");a._ioNotifyStart(e);if(a.config.debugAtAllCosts)g.send(f.query);else try{g.send(f.query)}catch(j){f.error=j,e.cancel()}a._ioWatch(e,R,D,S);return e};a.xhrGet=function(b){return a.xhr("GET",b)};a.rawXhrPost=a.xhrPost=function(b){return a.xhr("POST",b,!0)};a.rawXhrPut=a.xhrPut=function(b){return a.xhr("PUT",b,!0)};a.xhrDelete=function(b){return a.xhr("DELETE",
b)};a._isDocumentOk=function(a){a=a.status||0;return a>=200&&a<300||a==304||a==1223||!a};a._getText=function(b){var c;a.xhrGet({url:b,sync:!0,load:function(a){c=a}});return c};k.mixin(a.xhr,{_xhrObj:a._xhrObj,fieldToObject:d.fieldToObject,formToObject:d.toObject,objectToQuery:n.objectToQuery,formToQuery:d.toQuery,formToJson:d.toJson,queryToObject:n.queryToObject,contentHandlers:g,_ioSetArgs:a._ioSetArgs,_ioCancelAll:a._ioCancelAll,_ioNotifyStart:a._ioNotifyStart,_ioWatch:a._ioWatch,_ioAddQueryToUrl:a._ioAddQueryToUrl,
_isDocumentOk:a._isDocumentOk,_getText:a._getText,get:a.xhrGet,post:a.xhrPost,put:a.xhrPut,del:a.xhrDelete});return a.xhr})},"dojo/io-query":function(){define(["./_base/lang"],function(a){var h={};return{objectToQuery:function(l){var n=encodeURIComponent,e=[],d;for(d in l){var m=l[d];if(m!=h[d]){var f=n(d)+"=";if(a.isArray(m))for(var k=0,b=m.length;k<b;++k)e.push(f+n(m[k]));else e.push(f+n(m))}}return e.join("&")},queryToObject:function(h){for(var n=decodeURIComponent,h=h.split("&"),e={},d,m,f=0,
k=h.length;f<k;++f)if(m=h[f],m.length){var b=m.indexOf("=");b<0?(d=n(m),m=""):(d=n(m.slice(0,b)),m=n(m.slice(b+1)));typeof e[d]=="string"&&(e[d]=[e[d]]);a.isArray(e[d])?e[d].push(m):e[d]=m}return e}}})},"dojo/dom-form":function(){define(["./_base/lang","./dom","./io-query","./json"],function(a,h,l,n){var e={fieldToObject:function(a){var e=null;if(a=h.byId(a)){var f=a.name,k=(a.type||"").toLowerCase();if(f&&k&&!a.disabled)if(k=="radio"||k=="checkbox"){if(a.checked)e=a.value}else if(a.multiple){e=[];
for(a=[a.firstChild];a.length;)for(f=a.pop();f;f=f.nextSibling)if(f.nodeType==1&&f.tagName.toLowerCase()=="option")f.selected&&e.push(f.value);else{f.nextSibling&&a.push(f.nextSibling);f.firstChild&&a.push(f.firstChild);break}}else e=a.value}return e},toObject:function(d){for(var l={},d=h.byId(d).elements,f=0,k=d.length;f<k;++f){var b=d[f],o=b.name,j=(b.type||"").toLowerCase();if(o&&j&&"file|submit|image|reset|button".indexOf(j)<0&&!b.disabled){var n=l,p=o,b=e.fieldToObject(b);if(b!==null){var c=
n[p];typeof c=="string"?n[p]=[c,b]:a.isArray(c)?c.push(b):n[p]=b}if(j=="image")l[o+".x"]=l[o+".y"]=l[o].x=l[o].y=0}}return l},toQuery:function(a){return l.objectToQuery(e.toObject(a))},toJson:function(a,h){return n.stringify(e.toObject(a),null,h?4:0)}};return e})},"dojo/_base/fx":function(){define(["./kernel","./lang","../Evented","./Color","./connect","./sniff","../dom","../dom-style"],function(a,h,l,n,e,d,m,f){var k=h.mixin;a._Line=function(a,b){this.start=a;this.end=b};a._Line.prototype.getValue=
function(a){return(this.end-this.start)*a+this.start};a.Animation=function(b){k(this,b);if(h.isArray(this.curve))this.curve=new a._Line(this.curve[0],this.curve[1])};a.Animation.prototype=new l;a._Animation=a.Animation;h.extend(a.Animation,{duration:350,repeat:0,rate:20,_percent:0,_startRepeatCount:0,_getStep:function(){var a=this._percent,b=this.easing;return b?b(a):a},_fire:function(b,d){var e=d||[];if(this[b])if(a.config.debugAtAllCosts)this[b].apply(this,e);else try{this[b].apply(this,e)}catch(f){console.error("exception in animation handler for:",
b),console.error(f)}return this},play:function(a,b){this._delayTimer&&this._clearTimer();if(b)this._stopTimer(),this._active=this._paused=!1,this._percent=0;else if(this._active&&!this._paused)return this;this._fire("beforeBegin",[this.node]);var d=a||this.delay,e=h.hitch(this,"_play",b);if(d>0)return this._delayTimer=setTimeout(e,d),this;e();return this},_play:function(){this._delayTimer&&this._clearTimer();this._startTime=(new Date).valueOf();this._paused&&(this._startTime-=this.duration*this._percent);
this._active=!0;this._paused=!1;var a=this.curve.getValue(this._getStep());if(!this._percent){if(!this._startRepeatCount)this._startRepeatCount=this.repeat;this._fire("onBegin",[a])}this._fire("onPlay",[a]);this._cycle();return this},pause:function(){this._delayTimer&&this._clearTimer();this._stopTimer();if(!this._active)return this;this._paused=!0;this._fire("onPause",[this.curve.getValue(this._getStep())]);return this},gotoPercent:function(a,b){this._stopTimer();this._active=this._paused=!0;this._percent=
a;b&&this.play();return this},stop:function(a){this._delayTimer&&this._clearTimer();if(!this._timer)return this;this._stopTimer();if(a)this._percent=1;this._fire("onStop",[this.curve.getValue(this._getStep())]);this._active=this._paused=!1;return this},status:function(){if(this._active)return this._paused?"paused":"playing";return"stopped"},_cycle:function(){if(this._active){var a=((new Date).valueOf()-this._startTime)/this.duration;a>=1&&(a=1);this._percent=a;this.easing&&(a=this.easing(a));this._fire("onAnimate",
[this.curve.getValue(a)]);if(this._percent<1)this._startTimer();else{this._active=!1;if(this.repeat>0)this.repeat--,this.play(null,!0);else if(this.repeat==-1)this.play(null,!0);else if(this._startRepeatCount)this.repeat=this._startRepeatCount,this._startRepeatCount=0;this._percent=0;this._fire("onEnd",[this.node]);!this.repeat&&this._stopTimer()}}return this},_clearTimer:function(){clearTimeout(this._delayTimer);delete this._delayTimer}});var b=0,o=null,j={run:function(){}};h.extend(a.Animation,
{_startTimer:function(){if(!this._timer)this._timer=e.connect(j,"run",this,"_cycle"),b++;o||(o=setInterval(h.hitch(j,"run"),this.rate))},_stopTimer:function(){if(this._timer)e.disconnect(this._timer),this._timer=null,b--;b<=0&&(clearInterval(o),o=null,b=0)}});var s=d("ie")?function(a){var b=a.style;if(!b.width.length&&f.get(a,"width")=="auto")b.width="auto"}:function(){};a._fade=function(b){b.node=m.byId(b.node);var d=k({properties:{}},b),b=d.properties.opacity={};b.start=!("start"in d)?function(){return+f.get(d.node,
"opacity")||0}:d.start;b.end=d.end;b=a.animateProperty(d);e.connect(b,"beforeBegin",h.partial(s,d.node));return b};a.fadeIn=function(b){return a._fade(k({end:1},b))};a.fadeOut=function(b){return a._fade(k({end:0},b))};a._defaultEasing=function(a){return 0.5+Math.sin((a+1.5)*Math.PI)/2};var p=function(a){this._properties=a;for(var b in a){var d=a[b];if(d.start instanceof n)d.tempColor=new n}};p.prototype.getValue=function(a){var b={},d;for(d in this._properties){var e=this._properties[d],f=e.start;
f instanceof n?b[d]=n.blendColors(f,e.end,a,e.tempColor).toCss():h.isArray(f)||(b[d]=(e.end-f)*a+f+(d!="opacity"?e.units||"px":0))}return b};a.animateProperty=function(b){var d=b.node=m.byId(b.node);if(!b.easing)b.easing=a._defaultEasing;b=new a.Animation(b);e.connect(b,"beforeBegin",b,function(){var a={},b;for(b in this.properties){if(b=="width"||b=="height")this.node.display="block";var c=this.properties[b];h.isFunction(c)&&(c=c(d));c=a[b]=k({},h.isObject(c)?c:{end:c});if(h.isFunction(c.start))c.start=
c.start(d);if(h.isFunction(c.end))c.end=c.end(d);var e=b.toLowerCase().indexOf("color")>=0,j=function(a,b){var c={height:a.offsetHeight,width:a.offsetWidth}[b];if(c!==void 0)return c;c=f.get(a,b);return b=="opacity"?+c:e?c:parseFloat(c)};if("end"in c){if(!("start"in c))c.start=j(d,b)}else c.end=j(d,b);e?(c.start=new n(c.start),c.end=new n(c.end)):c.start=b=="opacity"?+c.start:parseFloat(c.start)}this.curve=new p(a)});e.connect(b,"onAnimate",h.hitch(f,"set",b.node));return b};a.anim=function(b,d,e,
f,h,j){return a.animateProperty({node:b,duration:e||a.Animation.prototype.duration,properties:d,easing:f,onEnd:h}).play(j||0)};return{_Line:a._Line,Animation:a.Animation,_fade:a._fade,fadeIn:a.fadeIn,fadeOut:a.fadeOut,_defaultEasing:a._defaultEasing,animateProperty:a.animateProperty,anim:a.anim}})},"dojo/_base/loader":function(){define(["./kernel","../has","require","module","./json","./lang","./array"],function(a,h,l,n,e,d,m){var f=function(a){return a.replace(/\./g,"/")},k=/\/\/>>built/,b=[],o=
[],j,s=function(a){j[a.mid]=1;for(var b,c,d=a.deps||[],e=0;e<d.length;e++)if(c=d[e],!(b=j[c.mid]))if(b===0||!s(c))return j[a.mid]=0,!1;return!0},p=function(){var a,c;j={};for(c in S)if(a=S[c],a.executed||a.noReqPluginCheck)j[c]=1;else{if(a.noReqPluginCheck!==0)a.noReqPluginCheck=/loadInit\!/.test(c)||/require\!/.test(c)?1:0;a.noReqPluginCheck?j[c]=1:a.injected!==A&&(j[c]=0)}for(var d=0,e=o.length;d<e;d++)if(a=o[d],!(c=j[a.mid]))if(c===0||!s(a))return;r.holdIdle();a=b;b=[];m.forEach(a,function(a){a(1)});
r.releaseIdle()},c=function(b,c,d){var e=/\(|\)/g,f=1;for(e.lastIndex=c;c=e.exec(b);)if(c[0]==")"?f-=1:f+=1,f==0)break;if(f!=0)throw"unmatched paren around character "+e.lastIndex+" in: "+b;return[a.trim(b.substring(d,e.lastIndex))+";\n",e.lastIndex]},g=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,i=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,q=/(^|\s)(require|define)\s*\(/m,u=function(a,b){var d,e,f,h=[],j=[];d=[];for(b=b||a.replace(g,function(a){i.lastIndex=
q.lastIndex=0;return i.test(a)||q.test(a)?"":a});d=i.exec(b);)e=i.lastIndex,f=e-d[0].length,e=c(b,e,f),d[2]=="loadInit"?h.push(e[0]):j.push(e[0]),i.lastIndex=e[1];d=h.concat(j);return d.length||!q.test(b)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 && dojo.loadInit("),d.join(""),d]:0},r=l.initSyncLoader(function(a,c,d){b.push(d);m.forEach(a.split(","),function(a){a=P(a,c.module);o.push(a);v(a)});p()},p,function(b,c){var d,e,f=[],g=[];if(k.test(c)||!(d=u(c)))return 0;e=b.mid+"-*loadInit";for(var h in P("dojo",
b).result.scopeMap)f.push(h),g.push('"'+h+'"');return"// xdomain rewrite of "+b.path+"\ndefine('"+e+"',{\n\tnames:"+a.toJson(f)+",\n\tdef:function("+f.join(",")+"){"+d[1]+"}});\n\ndefine("+a.toJson(f.concat(["dojo/loadInit!"+e]))+", function("+f.join(",")+"){\n"+d[0]+"});"}),t=r.sync,A=r.arrived,w=r.nonmodule,I=r.executing,R=r.executed,D=r.syncExecStack,S=r.modules,x=r.execQ,P=r.getModule,v=r.injectModule,B=r.setArrived,F=r.signal,C=r.finishExec,E=r.execModule,G=r.getLegacyMode;a.provide=function(a){var b=
D[0],c=d.mixin(P(f(a),l.module),{executed:I,result:d.getObject(a,!0)});B(c);if(b)(b.provides||(b.provides=[])).push(function(){c.result=d.getObject(a);delete c.provides;c.executed!==R&&C(c)});return c.result};h.add("config-publishRequireResult",1,0,0);a.require=function(a,b){var c=function(a,b){var c=P(f(a),l.module);if(D.length&&D[0].finish)D[0].finish.push(a);else{if(c.executed)return c.result;b&&(c.result=w);var d=G();v(c);d=G();c.executed!==R&&c.injected===A&&(r.holdIdle(),E(c),r.releaseIdle());
if(c.executed)return c.result;d==t?c.cjs?x.unshift(c):D.length&&(D[0].finish=[a]):x.push(c)}}(a,b);h("config-publishRequireResult")&&!d.exists(a)&&c!==void 0&&d.setObject(a,c);return c};a.loadInit=function(a){a()};a.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;l({paths:c})};a.platformRequire=function(b){for(var b=(b.common||[]).concat(b[a._name]||b["default"]||[]),c;b.length;)d.isArray(c=b.shift())?a.require.apply(a,c):a.require(c)};a.requireIf=a.requireAfterIf=function(b,c,
d){b&&a.require(c,d)};a.requireLocalization=function(a,b,c){l(["../i18n"],function(d){d.getLocalization(a,b,c)})};return{extractLegacyApiApplications:u,require:r.dojoRequirePlugin,loadInit:function(c,d,e){d([c],function(c){d(c.names,function(){for(var g="",h=[],i=0;i<arguments.length;i++)g+="var "+c.names[i]+"= arguments["+i+"]; ",h.push(arguments[i]);eval(g);var j=d.module,k=[],g={},l=[],q,i={provide:function(a){a=f(a);a=P(a,j);a!==j&&B(a)},require:function(a,b){a=f(a);b&&(P(a,j).result=w);l.push(a)},
requireLocalization:function(b,c,d){k.length||(k=["dojo/i18n"]);d=(d||a.locale).toLowerCase();b=f(b)+"/nls/"+(/root/i.test(d)?"":d+"/")+f(c);P(b,j).isXd&&k.push("dojo/i18n!"+b)},loadInit:function(a){a()}};try{for(q in i)g[q]=a[q],a[q]=i[q];c.def.apply(null,h)}catch(r){F("error",[{src:n.id,id:"failedDojoLoadInit"},r])}finally{for(q in i)a[q]=g[q]}l.length&&k.push("dojo/require!"+l.join(","));b.push(e);m.forEach(l,function(a){a=P(a,d.module);o.push(a);v(a)});p()})})}}})}}});
(function(){var a=this.require;a({cache:{}});!a.async&&a(["dojo"]);a.boot&&a.apply(null,a.boot)})();